In [ ]:
import os
import pandas as pd
import numpy as np
import requests

In [10]:
os.listdir()

['alunos', 'aulas', 'data', 'exercicios', 'exercicios_resolvidos']

In [11]:
exercicios = [i[:-6] for i in os.listdir("exercicios_resolvidos") if i.endswith(".ipynb")]
exercicios

['02 - introdução',
 '04 - objetos_simples',
 '05-Objetos_Compostos_1',
 '06-Objetos_Compostos_2',
 '07-Operadores_aritméticos_2026-03-23',
 '08-Operadores_relacionais_2026-03-24',
 '09-Operadores_lógicos_2026-03-25',
 '10-Estruturas_condicionais_2026-03-26',
 '11-Estruturas_repetição_2026-03-26',
 '12-Rotinas_2026-03-28',
 '13-Variáveis_Qualitativas_2026-03-30',
 '14-Variáveis_Quantitativas_2026-03-31',
 '15-Medidas_Resumo_1_2026-04-01',
 '16-Medidas_Resumo_2_2026-04-01']

In [12]:
with open("./alunos/GitHub_Alunos.txt", "r") as f:
    data = f.readlines()
data = data[1:]
data

['2. Alessandra Conti Gomes de Souza - https://github.com/alecgsbr-web/Aula-Phyton\n',
 '3. Aline de Carvalho - https://github.com/aline-bio/python-basico.git\n',
 '4. Bianca Nichele Kusma - https://github.com/biancankusma/python_basico.git\n',
 '5. Camilla Leitzke Toledo - https://github.com/camilaltoledo0502-art/Entregas-de-atividades-aula-Python-.git\n',
 '6. Camilla Maia Moraes - https://github.com/camss36/Python_b-sico_Camilla_Maia.git\n',
 '7. Carolina Zem - https://github.com/zemsacional/Aulas_Python\n',
 '8. Emanuele Oliveira Jarno - https://github.com/emanuelejarno/Aula-de-mestrado\n',
 '9. Gabriela Maria da Costa Ferreira - https://github.com/GbrielaMaria/Python\n',
 '10. Gabriela Marino Koerich - https://github.com/GabrielaKoerich/Mestrado-Python-Basico\n',
 '11. Hector Hugo Furini - https://github.com/hector-furini/Disciplina-PBp-Python\n',
 '12. Isabel de Farias Ribeiro - https://github.com/isabeldfribeiro/Disciplina_python\n',
 '13. Isadora Celine Rodrigues Carneiro Camargo - https://github.com/isacarneiro/python_basic_2026\n',
 '14. Julia Cardoso da Silva - https://github.com/cardosojulias/Mestrado_python_julia\n',
 '15. Julia Weber Ferraboli - https://github.com/jwferraboli/aulagithub.git\n',
 '16. Livia Mendes Zacharow Pedroso - https://github.com/Livia-Zacharow/aulas_python_doutorado.git\n',
 '17. Lucas Herrero Matias - https://github.com/lherreromatias/Disciplina_pyton\n',
 '18. Mario Kujbida - https://github.com/Mario-Kujbida/Python-B-sico.git\n',
 '19. Mateus Marchetto - https://github.com/marchettom/Disciplina-Python\n',
 '20. Matheus Schipanski - https://github.com/matcow/Aula-Python\n',
 '21. Natália Jeanegitz da Silva - https://github.com/njeanegitz/aula-python.git\n',
 '22. Natalia Zureck Xavier - https://github.com/NataliaZureck/AulaPythonBasico.git\n',
 '23. Nicholas Yuri Naufal - https://github.com/nicholasynaufal/Disciplina_Python.git\n',
 '24. Paulo Henrique Moro dos Santos - https://github.com/paulo-moro/disciplina_python_doc\n',
 '25. Rafael Uhlik Veiga - https://github.com/R-Zurik/Projeto-Inicial-Teste\n',
 '26. Rodrigo Alexandre Lusa - https://github.com/Rodrigo-Lusa/aulas_python_mestrado.git\n',
 '27. Sophia Pereira Ozorio - https://github.com/SophiaOzorio/mestrado_python\n',
 '28. Thais Agata Veiga Ferreira - https://github.com/tveigaferreira-hue/phyton-.git\n',
 '29. Yasmin Soares - https://github.com/yasminsoares01/aulas-Phyton']

In [ ]:
lista_alunos = [v[3:].strip().split(" - ") if k < 10 else v[4:].strip().split(" - ") for k, v in enumerate(data)]
lista_alunos[:4]

[['Alessandra Conti Gomes de Souza',
  'https://github.com/alecgsbr-web/Aula-Phyton'],
 ['Aline de Carvalho', 'https://github.com/aline-bio/python-basico.git'],
 ['Bianca Nichele Kusma', 'https://github.com/biancankusma/python_basico.git'],
 ['Camilla Leitzke Toledo',
  'https://github.com/camilaltoledo0502-art/Entregas-de-atividades-aula-Python-.git'],
 ['Camilla Maia Moraes',
  'https://github.com/camss36/Python_b-sico_Camilla_Maia.git'],
 ['Carolina Zem', 'https://github.com/zemsacional/Aulas_Python'],
 ['Emanuele Oliveira Jarno',
  'https://github.com/emanuelejarno/Aula-de-mestrado'],
 ['Gabriela Maria da Costa Ferreira',
  'https://github.com/GbrielaMaria/Python'],
 ['Gabriela Marino Koerich',
  'https://github.com/GabrielaKoerich/Mestrado-Python-Basico'],
 ['Hector Hugo Furini',
  'https://github.com/hector-furini/Disciplina-PBp-Python'],
 ['Isabel de Farias Ribeiro',
  'https://github.com/isabeldfribeiro/Disciplina_python'],
 ['Isadora Celine Rodrigues Carneiro Camargo',
  'https://github.com/isacarneiro/python_basic_2026'],
 ['Julia Cardoso da Silva',
  'https://github.com/cardosojulias/Mestrado_python_julia'],
 ['Julia Weber Ferraboli', 'https://github.com/jwferraboli/aulagithub.git'],
 ['Livia Mendes Zacharow Pedroso',
  'https://github.com/Livia-Zacharow/aulas_python_doutorado.git'],
 ['Lucas Herrero Matias',
  'https://github.com/lherreromatias/Disciplina_pyton'],
 ['Mario Kujbida', 'https://github.com/Mario-Kujbida/Python-B-sico.git'],
 ['Mateus Marchetto', 'https://github.com/marchettom/Disciplina-Python'],
 ['Matheus Schipanski', 'https://github.com/matcow/Aula-Python'],
 ['Natália Jeanegitz da Silva',
  'https://github.com/njeanegitz/aula-python.git'],
 ['Natalia Zureck Xavier',
  'https://github.com/NataliaZureck/AulaPythonBasico.git'],
 ['Nicholas Yuri Naufal',
  'https://github.com/nicholasynaufal/Disciplina_Python.git'],
 ['Paulo Henrique Moro dos Santos',
  'https://github.com/paulo-moro/disciplina_python_doc'],
 ['Rafael Uhlik Veiga', 'https://github.com/R-Zurik/Projeto-Inicial-Teste'],
 ['Rodrigo Alexandre Lusa',
  'https://github.com/Rodrigo-Lusa/aulas_python_mestrado.git'],
 ['Sophia Pereira Ozorio', 'https://github.com/SophiaOzorio/mestrado_python'],
 ['Thais Agata Veiga Ferreira',
  'https://github.com/tveigaferreira-hue/phyton-.git'],
 ['Yasmin Soares', 'https://github.com/yasminsoares01/aulas-Phyton']]

In [14]:
data = {
    "nomes": [i[0] for i in lista_alunos],
    "github": [i[1] for i in lista_alunos],
}
df = pd.DataFrame(data)
df.head()

,nomes,github
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...

In [15]:
df_aulas = df.copy()
for i in exercicios:
    df_aulas.loc[:, i] = False
df_aulas.head()

,nomes,github,02 - introdução,04 - objetos_simples,05-Objetos_Compostos_1,06-Objetos_Compostos_2,07-Operadores_aritméticos_2026-03-23,08-Operadores_relacionais_2026-03-24,09-Operadores_lógicos_2026-03-25,10-Estruturas_condicionais_2026-03-26,11-Estruturas_repetição_2026-03-26,12-Rotinas_2026-03-28,13-Variáveis_Qualitativas_2026-03-30,14-Variáveis_Quantitativas_2026-03-31,15-Medidas_Resumo_1_2026-04-01,16-Medidas_Resumo_2_2026-04-01
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
df_aulas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 16 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   nomes                                  28 non-null     object
 1   github                                 28 non-null     object
 2   02 - introdução                        28 non-null     bool
 3   04 - objetos_simples                   28 non-null     bool
 4   05-Objetos_Compostos_1                 28 non-null     bool
 5   06-Objetos_Compostos_2                 28 non-null     bool
 6   07-Operadores_aritméticos_2026-03-23   28 non-null     bool
 7   08-Operadores_relacionais_2026-03-24   28 non-null     bool
 8   09-Operadores_lógicos_2026-03-25       28 non-null     bool
 9   10-Estruturas_condicionais_2026-03-26  28 non-null     bool
 10  11-Estruturas_repetição_2026-03-26     28 non-null     bool
 11  12-Rotinas_2026-03-28                  28 non-null     bool
 12  13-Variáveis_Qualitativas_2026-03-30   28 non-null     bool
 13  14-Variáveis_Quantitativas_2026-03-31  28 non-null     bool
 14  15-Medidas_Resumo_1_2026-04-01         28 non-null     bool
 15  16-Medidas_Resumo_2_2026-04-01         28 non-null     bool
dtypes: bool(14), object(2)
memory usage: 968.0+ bytes

In [44]:
url = df_aulas['github'][0]
print(url)
response = requests.get(url)
if response.status_code == 200:
    data = response.text.split("name")
data = [i for i in data if '.ipynb","' in i]
data = [i.split('","path')[0][3:] for i in data]
data

https://github.com/alecgsbr-web/Aula-Phyton

['02 - introdução.ipynb',
 '04 - objetos_simples.ipynb',
 '05-Objetos_Compostos_1.ipynb',
 '06-Objetos_Compostos_2.ipynb',
 '07-Operadores_aritméticos_2026-03-23.ipynb',
 '08-Operadores_relacionais_2026-03-24.ipynb',
 '09-Operadores_lógicos_2026-03-25.ipynb',
 '10-Estruturas_condicionais_2026-03-26.ipynb',
 '11-Estruturas_repetição_2026-03-26.ipynb',
 '12-Rotinas_2026-03-28.ipynb',
 '13-Variáveis_Qualitativas_2026-03-30.ipynb',
 '14-Variáveis_Quantitativas_2026-03-31.ipynb',
 '15-Medidas_Resumo_1_2026-04-01.ipynb',
 '16-Medidas_Resumo_2_2026-04-01.ipynb',
 'Segundo_note.ipynb',
 'primeiro_note.ipynb']