In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns # still useful for color palettes/style
import numpy as np

https://1drv.ms/v/c/808ebfd9a0d86213/IQDfZDtGj1onTY3-cgY4y03kAeR87GU2oxIY2gdliJ3-MEQ?e=vAY90t

In [31]:
df = pd.DataFrame({'variavel': np.random.normal(loc=0, scale=1, size=100)})
df.head()

   variavel
0  1.136180
1 -0.482246
2 -0.466983
3  0.407379
4  0.334106

In [32]:
df.describe()

         variavel
count  100.000000
mean     0.040338
std      0.865079
min     -2.462003
25%     -0.484951
50%      0.103721
75%      0.495826
max      1.930968

In [33]:
bins = [-3, -1.2, -1, 0, 1.2, 2, 3]
df['ordinal'] = pd.cut(df['variavel'], bins=bins, labels=['Cat A', 'Cat B', 'Cat C', 'Cat D', 'Cat E', 'Cat F'])
df.head()

   variavel ordinal
0  1.136180   Cat D
1 -0.482246   Cat C
2 -0.466983   Cat C
3  0.407379   Cat D
4  0.334106   Cat D

In [34]:
df['nominal'] = pd.qcut(df['variavel'], q=6, labels=['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6'])
df.head()

   variavel ordinal nominal
0  1.136180   Cat D      Q6
1 -0.482246   Cat C      Q2
2 -0.466983   Cat C      Q2
3  0.407379   Cat D      Q5
4  0.334106   Cat D      Q4

In [35]:
df.head()

   variavel ordinal nominal
0  1.136180   Cat D      Q6
1 -0.482246   Cat C      Q2
2 -0.466983   Cat C      Q2
3  0.407379   Cat D      Q5
4  0.334106   Cat D      Q4

In [43]:
freq_nominal = (
    df['nominal'].value_counts()
    .sort_index()
    .to_frame()
    .rename(columns={'nominal': 'abso_simp'})
    .assign(relat_simp=df['nominal'].value_counts(normalize=True))
)
freq_nominal

    abso_simp  relat_simp
Q1         17        0.17
Q2         17        0.17
Q3         16        0.16
Q4         17        0.17
Q5         16        0.16
Q6         17        0.17

In [45]:
freq_ordinal = (
    df['ordinal'].value_counts()
    .sort_index()
    .to_frame()
    .rename(columns={'ordinal': 'abso_simp'})
    .assign(relat_simp=df['ordinal'].value_counts(normalize=True))
)
freq_ordinal

       abso_simp  relat_simp
Cat A          8        0.08
Cat B          2        0.02
Cat C         32        0.32
Cat D         50        0.50
Cat E          8        0.08
Cat F          0        0.00

In [51]:
freq_ordinal = (
    freq_ordinal.assign(absol_acum=freq_ordinal['abso_simp'].cumsum())
    .assign(relat_acum=freq_ordinal['relat_simp'].cumsum())
)
freq_ordinal

       abso_simp  relat_simp  absol_acum  relat_acum
Cat A          8        0.08           8        0.08
Cat B          2        0.02          10        0.10
Cat C         32        0.32          42        0.42
Cat D         50        0.50          92        0.92
Cat E          8        0.08         100        1.00
Cat F          0        0.00         100        1.00

In [52]:
freq_ordinal

       abso_simp  relat_simp  absol_acum  relat_acum
Cat A          8        0.08           8        0.08
Cat B          2        0.02          10        0.10
Cat C         32        0.32          42        0.42
Cat D         50        0.50          92        0.92
Cat E          8        0.08         100        1.00
Cat F          0        0.00         100        1.00

In [53]:
freq_nominal

    abso_simp  relat_simp
Q1         17        0.17
Q2         17        0.17
Q3         16        0.16
Q4         17        0.17
Q5         16        0.16
Q6         17        0.17

In [ ]:
def gerar_cepa(codigo: str) -> list:
    num = np.random.randint(300, 500)
    cepa = f"{codigo}_"*num
    cepa = cepa.split("_")[:-1]
    return cepa

In [3]:
cepas = [
    "Cepa A",
    "Cepa B",
    "Cepa C",
    "Cepa D",
    "Cepa E",
    "Cepa F",
    "Total",
]
cepa_final = [gerar_cepa(cepa) for cepa in cepas]
cepa = np.array(
                cepa_final[0] +
                cepa_final[1] +
                cepa_final[2] +
                cepa_final[3] +
                cepa_final[4] +
                cepa_final[5]
)
cepa.shape

(2474,)

In [ ]:
cepa[:10]

array(['Cepa A', 'Cepa A', 'Cepa A', 'Cepa A', 'Cepa A', 'Cepa A',
       'Cepa A', 'Cepa A', 'Cepa A', 'Cepa A'], dtype='<U6')

In [5]:
np.random.shuffle(cepa)
cepa[:10]

array(['Cepa D', 'Cepa A', 'Cepa B', 'Cepa F', 'Cepa E', 'Cepa C',
       'Cepa B', 'Cepa F', 'Cepa A', 'Cepa D'], dtype='<U6')

In [6]:
df = pd.DataFrame(cepa, columns=["Cepa"])
df.head()

     Cepa
0  Cepa D
1  Cepa A
2  Cepa B
3  Cepa F
4  Cepa E

In [7]:
tabela_freq = (
                df.value_counts()
                .sort_index()
                .to_frame()
                .rename(columns={0: "absol_simp"})
                .assign(
                    relat_simp=df['Cepa'].value_counts(normalize=True).values
                )
                .round(3)
)
soma = tabela_freq.sum().to_frame().T
tabela_nominal = pd.concat((tabela_freq, soma), axis=0)
tabela_nominal.index = cepas
tabela_nominal

        absol_simp  relat_simp
Cepa A       349.0       0.193
Cepa B       404.0       0.171
Cepa C       478.0       0.168
Cepa D       422.0       0.164
Cepa E       416.0       0.163
Cepa F       405.0       0.141
Total       2474.0       1.000

In [8]:
tabela_ordinal = (
                tabela_nominal.assign(
                    absol_acum=tabela_nominal["absol_simp"].cumsum(),
                    relat_acum=tabela_nominal["relat_simp"].cumsum()
                )
)
tabela_ordinal.loc['Total', ['absol_acum', 'relat_acum']] = np.nan
tabela_ordinal

        absol_simp  relat_simp  absol_acum  relat_acum
Cepa A       349.0       0.193       349.0       0.193
Cepa B       404.0       0.171       753.0       0.364
Cepa C       478.0       0.168      1231.0       0.532
Cepa D       422.0       0.164      1653.0       0.696
Cepa E       416.0       0.163      2069.0       0.859
Cepa F       405.0       0.141      2474.0       1.000
Total       2474.0       1.000         NaN         NaN