# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Sim. Podendo ser inclusive de diferentes classes como lista, tupla, set, dicionário, array e dataframe

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [1]:
genes = [
    'isg15',
    'hur',
    'ifna',
    'tnfa',
    'atpsf1a',
]
genes

['isg15', 'hur', 'ifna', 'tnfa', 'atpsf1a']

In [2]:
index_gene = 0
gene_1 = [
    len(genes[index_gene]),         # número de caracteres presentes no nome do gene
    genes[index_gene][:2],          # primeiras duas letras do nome do gene
    genes[index_gene].count('a'),   # número de vezes que a letra 'a' aparece no nome do gene
    'hu' in genes[index_gene]       # verificar se a sequência 'hu' está presente no nome do gene
]
gene_1

[5, 'is', 0, False]

In [3]:
index_gene = 1
gene_2 = [
    len(genes[index_gene]),         # número de caracteres presentes no nome do gene
    genes[index_gene][:2],          # primeiras duas letras do nome do gene
    genes[index_gene].count('a'),   # número de vezes que a letra 'a' aparece no nome do gene
    'hu' in genes[index_gene]       # verificar se a sequência 'hu' está presente no nome do gene
]
gene_2

[3, 'hu', 0, True]

In [4]:
index_gene = 2
gene_3 = [
    len(genes[index_gene]),         # número de caracteres presentes no nome do gene
    genes[index_gene][:2],          # primeiras duas letras do nome do gene
    genes[index_gene].count('a'),   # número de vezes que a letra 'a' aparece no nome do gene
    'hu' in genes[index_gene]       # verificar se a sequência 'hu' está presente no nome do gene
]
gene_3

[4, 'if', 1, False]

In [5]:
index_gene = 3
gene_4 = [
    len(genes[index_gene]),         # número de caracteres presentes no nome do gene
    genes[index_gene][:2],          # primeiras duas letras do nome do gene
    genes[index_gene].count('a'),   # número de vezes que a letra 'a' aparece no nome do gene
    'hu' in genes[index_gene]       # verificar se a sequência 'hu' está presente no nome do gene
]
gene_4

[4, 'tn', 1, False]

In [6]:
index_gene = 4
gene_5 = [
    len(genes[index_gene]),         # número de caracteres presentes no nome do gene
    genes[index_gene][:2],          # primeiras duas letras do nome do gene
    genes[index_gene].count('a'),   # número de vezes que a letra 'a' aparece no nome do gene
    'hu' in genes[index_gene]       # verificar se a sequência 'hu' está presente no nome do gene
]
gene_5

[7, 'at', 2, False]

In [7]:
matrix_genes = [
    gene_1,
    gene_2,
    gene_3,
    gene_4,
    gene_5
]
matrix_genes

[[5, 'is', 0, False],
 [3, 'hu', 0, True],
 [4, 'if', 1, False],
 [4, 'tn', 1, False],
 [7, 'at', 2, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [8]:
import numpy as np

In [9]:
array_genes = np.array(matrix_genes.copy())
array_genes

array([['5', 'is', '0', 'False'],
       ['3', 'hu', '0', 'True'],
       ['4', 'if', '1', 'False'],
       ['4', 'tn', '1', 'False'],
       ['7', 'at', '2', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [10]:
array_genes[2, :]

array(['4', 'if', '1', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [11]:
array_genes[:, -1]

array(['False', 'True', 'False', 'False', 'False'], dtype='<U21')

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [12]:
array_genes

array([['5', 'is', '0', 'False'],
       ['3', 'hu', '0', 'True'],
       ['4', 'if', '1', 'False'],
       ['4', 'tn', '1', 'False'],
       ['7', 'at', '2', 'False']], dtype='<U21')

In [13]:
array_genes[[1, 3], 1:3]

array([['hu', '0'],
       ['tn', '1']], dtype='<U21')

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [14]:
genes_dict = {
    genes[0]: gene_1,
    genes[1]: gene_2,
    genes[2]: gene_3,
    genes[3]: gene_4,
    genes[4]: gene_5,
}
genes_dict

{'isg15': [5, 'is', 0, False],
 'hur': [3, 'hu', 0, True],
 'ifna': [4, 'if', 1, False],
 'tnfa': [4, 'tn', 1, False],
 'atpsf1a': [7, 'at', 2, False]}

In [15]:
import pandas as pd

In [16]:
df_genes = pd.DataFrame(genes_dict.copy())
df_genes

   isg15   hur   ifna   tnfa atpsf1a
0      5     3      4      4       7
1     is    hu     if     tn      at
2      0     0      1      1       2
3  False  True  False  False   False

In [17]:
df_genes = df_genes.transpose()
df_genes

         0   1  2      3
isg15    5  is  0  False
hur      3  hu  0   True
ifna     4  if  1  False
tnfa     4  tn  1  False
atpsf1a  7  at  2  False

In [18]:
df_genes.rename(columns={
                0: 'num_letras',
                1: 'primeiras_duas_letras',
                2: 'num_a',
                3: 'contains_hu'
            }, inplace=True)
df_genes

        num_letras primeiras_duas_letras num_a contains_hu
isg15            5                    is     0       False
hur              3                    hu     0        True
ifna             4                    if     1       False
tnfa             4                    tn     1       False
atpsf1a          7                    at     2       False

In [19]:
df_genes.to_csv('./data/df_genes_aula6exer7.csv', index=True)

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [20]:
df_genes[['num_letras', 'num_a']]

        num_letras num_a
isg15            5     0
hur              3     0
ifna             4     1
tnfa             4     1
atpsf1a          7     2

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [21]:
df_genes.loc[['isg15', 'ifna'], 'contains_hu']

isg15    False
ifna     False
Name: contains_hu, dtype: object

In [22]:
df_genes.iloc[[0, 2], -1]

isg15    False
ifna     False
Name: contains_hu, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [23]:
df = pd.read_csv('./data/data.csv')
df.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [24]:
dict_dados = {'num_entradas': len(df)}
dict_dados

{'num_entradas': 36634}

In [25]:
df.dtypes

policyID                int64
statecode              object
county                 object
eq_site_limit         float64
hu_site_limit         float64
fl_site_limit         float64
fr_site_limit         float64
tiv_2011              float64
tiv_2012              float64
eq_site_deductible    float64
hu_site_deductible    float64
fl_site_deductible    float64
fr_site_deductible      int64
point_latitude        float64
point_longitude       float64
line                   object
construction           object
point_granularity       int64
dtype: object

In [26]:
df.dtypes.value_counts()

float64    11
object      4
int64       3
dtype: int64

In [27]:
dict_dados['classes_colunas'] = df.dtypes.value_counts().index.astype(str).tolist()
dict_dados['num_elementos_por_classe'] = df.dtypes.value_counts().values.astype(str).tolist()
dict_dados

{'num_entradas': 36634,
 'classes_colunas': ['float64', 'object', 'int64'],
 'num_elementos_por_classe': ['11', '4', '3']}

In [28]:
colunas = df.columns[[0,3,8]]
df[colunas].describe()

            policyID  eq_site_limit      tiv_2012
count   36634.000000   3.663400e+04  3.663400e+04
mean   548661.937189   7.314780e+05  2.571004e+06
std    259912.926494   1.752300e+07  2.036777e+07
min    100074.000000   0.000000e+00  7.337000e+01
25%    323647.750000   0.000000e+00  5.401351e+04
50%    548525.000000   0.000000e+00  2.416310e+05
75%    774252.000000   0.000000e+00  1.128871e+06
max    999971.000000   2.160000e+09  1.701000e+09

In [29]:
medidas_resumo = df[colunas].describe().iloc[[1,2,6]]
medidas_resumo

           policyID  eq_site_limit      tiv_2012
mean  548661.937189   7.314780e+05  2.571004e+06
std   259912.926494   1.752300e+07  2.036777e+07
75%   774252.000000   0.000000e+00  1.128871e+06

In [30]:
dict_dados['media'] = medidas_resumo.loc['mean', :].to_list()
dict_dados['desvio'] = medidas_resumo.loc['std', :].to_list()
dict_dados['quartio'] = medidas_resumo.loc['75%', :].to_list()

dict_dados

{'num_entradas': 36634,
 'classes_colunas': ['float64', 'object', 'int64'],
 'num_elementos_por_classe': ['11', '4', '3'],
 'media': [548661.9371894961, 731478.0068460993, 2571004.0973420865],
 'desvio': [259912.9264939009, 17523003.588415086, 20367766.569178067],
 'quartio': [774252.0, 0.0, 1128871.1824999999]}

In [42]:
for i in df.dtypes.value_counts().index:
    print(str(i))

float64
object
int64

In [43]:
for i in df.dtypes.value_counts().values:
    print(int(i))

11
4
3