# Exercício:

## 01 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:

In [1]:
a = 2.0 + 3.0 / 5.0
a

2.6

In [2]:
b = (a + 10.2) - 5.0 * 2.0
b

2.799999999999999

In [3]:
c = a / b + 33.8
c

34.72857142857143

In [4]:
d = a / (b + c)
d

0.0692805481537876

In [5]:
e = d * 2
e

0.1385610963075752

## 02 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:

In [6]:
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
lista_a

[2.0, 3.0, 5.0, 10, 20, 30]

In [7]:
lista_b = lista_a * 2
lista_b

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

In [8]:
lista_c = lista_a + lista_b
lista_c

[2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30]

In [9]:
try:
    lista_d = lista_a / (lista_b * lista_c)
    print(lista_d)
except TypeError as error:
    print(f"Error: {error}")

Error: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01, instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [10]:
lista_simples = [a, b, c, d, e]
lista_simples

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752]

In [11]:
import numpy as np

In [12]:
lista_sqrt = list(np.sqrt(lista_simples))
lista_sqrt

[1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

In [13]:
lista_concat = lista_simples + lista_sqrt
lista_concat

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752,
 1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [14]:
array_sqrt = np.array(lista_concat * 2)
array_sqrt

array([ 2.6       ,  2.8       , 34.72857143,  0.06928055,  0.1385611 ,
        1.61245155,  1.67332005,  5.89309523,  0.26321198,  0.37223796,
        2.6       ,  2.8       , 34.72857143,  0.06928055,  0.1385611 ,
        1.61245155,  1.67332005,  5.89309523,  0.26321198,  0.37223796])

In [15]:
array_sqrt_reshape = array_sqrt.reshape(5, 4)
array_sqrt_reshape

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [16]:
mean_columns = list(array_sqrt_reshape.mean(axis=0))
mean_columns

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]

## 06 – O atributo shape pertence ao escopo dos objetos de classe numpy array. Ela retorna uma tupla onde o primeiro valor é o número de linhas e o segundo valor o de colunas contidas no array. Usando a informação do número total de valores presentes no numpy array do exercício 4 insira neste array a lista obtida no exercício 5. Recupere o array.
Obs.:  Atributos não usam () na chamada.

In [17]:
num_itens_array = array_sqrt_reshape.shape[0] * array_sqrt_reshape.shape[1]
num_itens_array

20

In [18]:
array_mean = np.insert(arr=array_sqrt_reshape, obj=num_itens_array, values=mean_columns)
array_mean

array([ 2.6       ,  2.8       , 34.72857143,  0.06928055,  0.1385611 ,
        1.61245155,  1.67332005,  5.89309523,  0.26321198,  0.37223796,
        2.6       ,  2.8       , 34.72857143,  0.06928055,  0.1385611 ,
        1.61245155,  1.67332005,  5.89309523,  0.26321198,  0.37223796,
        7.88073291,  2.14941306,  7.88073291,  2.14941306])

In [19]:
array_mean.shape

(24,)

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [20]:
import pandas as pd

In [21]:
df = pd.DataFrame(array_mean.reshape(-1, 4))
df

           0         1          2         3
0   2.600000  2.800000  34.728571  0.069281
1   0.138561  1.612452   1.673320  5.893095
2   0.263212  0.372238   2.600000  2.800000
3  34.728571  0.069281   0.138561  1.612452
4   1.673320  5.893095   0.263212  0.372238
5   7.880733  2.149413   7.880733  2.149413

In [22]:
df_round = df.copy().round(3)
df_round

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [23]:
df_mean_lines = df_round.mean(axis=1)
df_mean_lines

0    10.04950
1     2.32925
2     1.50875
3     9.13725
4     2.05025
5     5.01500
dtype: float64

In [24]:
df_round['mean'] = df_mean_lines
df_round

        0      1       2      3      mean
0   2.600  2.800  34.729  0.069  10.04950
1   0.139  1.612   1.673  5.893   2.32925
2   0.263  0.372   2.600  2.800   1.50875
3  34.729  0.069   0.139  1.612   9.13725
4   1.673  5.893   0.263  0.372   2.05025
5   7.881  2.149   7.881  2.149   5.01500

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [25]:
df_round.loc[:, 'mean'].describe()

count     6.000000
mean      5.015000
std       3.758615
min       1.508750
25%       2.120000
50%       3.672125
75%       8.106688
max      10.049500
Name: mean, dtype: float64

In [26]:
df_round.T.loc[:, 5].describe()

count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64

In [27]:
df_round.loc[5, :].describe()

count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [29]:
df_round.rename(columns={"mean": "Média"}, index={5: "Média"}, inplace=True)
df_round

            0      1       2      3     Média
0       2.600  2.800  34.729  0.069  10.04950
1       0.139  1.612   1.673  5.893   2.32925
2       0.263  0.372   2.600  2.800   1.50875
3      34.729  0.069   0.139  1.612   9.13725
4       1.673  5.893   0.263  0.372   2.05025
Média   7.881  2.149   7.881  2.149   5.01500

In [31]:
media_medias = df_round.iloc[-1, -1]
media_medias

5.015000000000001

In [32]:
import os

os.listdir()

['aulas', 'data', 'exercicios']

In [34]:
df_round.to_csv("./data/df_round_2026-03-25.csv")