# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [3]:
a = 2.0 + 3.0 / 5.0 == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a / b + 33.8 < 100
d = 5 != a / (b + c)
e = 33 == d * 2

print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")
print(f"d: {d}")
print(f"e: {e}")

a: False
b: True
c: True
d: True
e: False

## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [5]:
bool_1 = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
bool_2 = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
bool_3 = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
bool_4 = ['a',1,True,'b',0,False] > ['a',True,1]
bool_5 = ['a',1,True,'b',0,False] == 1
bool_6 = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

print(f"bool_1: {bool_1}")
print(f"bool_2: {bool_2}")
print(f"bool_3: {bool_3}")
print(f"bool_4: {bool_4}")
print(f"bool_5: {bool_5}")
print(f"bool_6: {bool_6}")

bool_1: False
bool_2: True
bool_3: False
bool_4: True
bool_5: False
bool_6: True

In [6]:
bool_1 = ('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)
bool_2 = ['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)
bool_3 = ['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]
bool_4 = ['a',1,True,'b',0,False] < ['a',True,1]
bool_5 = ['a',1,True,'b',0,False] != 1
bool_6 = ['a',True,1] > ['a',True,1] >= ['a',1,True,'b',0,False]

print(f"bool_1: {bool_1}")
print(f"bool_2: {bool_2}")
print(f"bool_3: {bool_3}")
print(f"bool_4: {bool_4}")
print(f"bool_5: {bool_5}")
print(f"bool_6: {bool_6}")

bool_1: True
bool_2: False
bool_3: True
bool_4: False
bool_5: True
bool_6: False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [7]:
import pandas as pd

In [ ]:
df = pd.read_csv("./data/df_round_2026-03-25.csv", index_col="Unnamed: 0")
df

            0      1       2      3     Média
0       2.600  2.800  34.729  0.069  10.04950
1       0.139  1.612   1.673  5.893   2.32925
2       0.263  0.372   2.600  2.800   1.50875
3      34.729  0.069   0.139  1.612   9.13725
4       1.673  5.893   0.263  0.372   2.05025
Média   7.881  2.149   7.881  2.149   5.01500

In [12]:
df = df.round(2)
df

           0     1      2     3  Média
0       2.60  2.80  34.73  0.07  10.05
1       0.14  1.61   1.67  5.89   2.33
2       0.26  0.37   2.60  2.80   1.51
3      34.73  0.07   0.14  1.61   9.14
4       1.67  5.89   0.26  0.37   2.05
Média   7.88  2.15   7.88  2.15   5.02

## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [13]:
import numpy as np

In [14]:
df.shape

(6, 5)

In [16]:
array_ones = np.ones(df.shape)
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [17]:
df == array_ones

           0      1      2      3  Média
0      False  False  False  False  False
1      False  False  False  False  False
2      False  False  False  False  False
3      False  False  False  False  False
4      False  False  False  False  False
Média  False  False  False  False  False

In [18]:
df[df == array_ones]

        0   1   2   3  Média
0     NaN NaN NaN NaN    NaN
1     NaN NaN NaN NaN    NaN
2     NaN NaN NaN NaN    NaN
3     NaN NaN NaN NaN    NaN
4     NaN NaN NaN NaN    NaN
Média NaN NaN NaN NaN    NaN

In [19]:
df[df == array_ones].count()

0        0
1        0
2        0
3        0
Média    0
dtype: int64

In [20]:
df[df == array_ones].count().sum()

0

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [22]:
df[df > array_ones].count().sum()

22

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [23]:
df[df <= array_ones].count().sum()

8

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [32]:
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
array_zeros = np.zeros(df.shape)
array_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
array_zeros < df

          0     1     2     3  Média
0      True  True  True  True   True
1      True  True  True  True   True
2      True  True  True  True   True
3      True  True  True  True   True
4      True  True  True  True   True
Média  True  True  True  True   True

In [39]:
df < array_ones

           0      1      2      3  Média
0      False  False  False   True  False
1       True  False  False  False  False
2       True   True  False  False  False
3      False   True   True  False  False
4      False  False   True   True  False
Média  False  False  False  False  False

In [35]:
df[(array_zeros < df) & (df < array_ones)]

          0     1     2     3  Média
0       NaN   NaN   NaN  0.07    NaN
1      0.14   NaN   NaN   NaN    NaN
2      0.26  0.37   NaN   NaN    NaN
3       NaN  0.07  0.14   NaN    NaN
4       NaN   NaN  0.26  0.37    NaN
Média   NaN   NaN   NaN   NaN    NaN

In [40]:
df[(array_zeros < df) & (df < array_ones)].count().sum()

8

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [41]:
df['Média']

0        10.05
1         2.33
2         1.51
3         9.14
4         2.05
Média     5.02
Name: Média, dtype: float64

In [43]:
df['Média'] <= 5

0        False
1         True
2         True
3        False
4         True
Média    False
Name: Média, dtype: bool

In [46]:
list(df['Média'] <= 5).count(True)

3

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [49]:
df.loc['Média', :] < 5

0        False
1         True
2        False
3         True
Média    False
Name: Média, dtype: bool

In [50]:
list(df.loc['Média', :] <= 5).count(True)

2