# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [1]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

print(f"p: {p} \n q: {q} \n r: {r} \n s: {s} \n t: {t} \n")
print(p and q and r and s and t)

p: False
 q: True
 r: True
 s: True
 t: False

False

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [2]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

print(f"p: {p} \n q: {q} \n r: {r} \n s: {s} \n t: {t} \n u: {u} \n")
print(p or q or r or s or t or u)

p: False
 q: True
 r: False
 s: True
 t: False
 u: True

True

In [3]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

print(f"p: {p} \n q: {not q} \n r: {r} \n s: {not s} \n t: {t} \n u: {not u} \n")
print(p or not q or r or not s or t or not u)

p: False
 q: False
 r: False
 s: False
 t: False
 u: False

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("./data/df_round_2026-03-25.csv", index_col="Unnamed: 0").round(2)
df

           0     1      2     3  Média
0       2.60  2.80  34.73  0.07  10.05
1       0.14  1.61   1.67  5.89   2.33
2       0.26  0.37   2.60  2.80   1.51
3      34.73  0.07   0.14  1.61   9.14
4       1.67  5.89   0.26  0.37   2.05
Média   7.88  2.15   7.88  2.15   5.02

In [6]:
p = list(df.iloc[1, :])
q = list(df.iloc[2, :])
r = list(df.iloc[3, :])

print(f"Segunda linha: {p}")
print(f"Terceira linha: {q}")
print(f"Quarta linha: {r}\n")

print(f"A segunda linha é igual a terceira? {p == q}")
print(f"A terceira linha é igual a quarta? {q == r}\n")

print(f"A segunda linha é igual a terceira ou a terceira linha é igual a quarta?: {p == q or q == r}")

Segunda linha: [0.14, 1.61, 1.67, 5.89, 2.33]
Terceira linha: [0.26, 0.37, 2.6, 2.8, 1.51]
Quarta linha: [34.73, 0.07, 0.14, 1.61, 9.14]

A segunda linha é igual a terceira? False
A terceira linha é igual a quarta? False

A segunda linha é igual a terceira ou a terceira linha é igual a quarta?: False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [7]:
p, q, r, s, t = df.iloc[0, :]

print(f"{p} >= 10? {p >= 10}")
print(f"{q} >= 10? {q >= 10}")
print(f"{r} >= 10? {r >= 10}")
print(f"{s} >= 10? {s >= 10}")
print(f"{t} >= 10? {t >= 10}\n")

p >= 10 and q >= 10 and r >= 10 and s >= 10 and t >= 10

2.6 >= 10? False
2.8 >= 10? False
34.73 >= 10? True
0.07 >= 10? False
10.05 >= 10? True

False

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [8]:
p, q, r, s, t, u = df.iloc[:, 2]

p_entre = 0 <= p < 40
q_entre = 0 <= q < 40
r_entre = 0 <= r < 40
s_entre = 0 <= s < 40
t_entre = 0 <= t < 40
u_entre = 0 <= u < 40

print(f"0 <= {p} < 40? {p_entre}")
print(f"0 <= {q} < 40? {q_entre}")
print(f"0 <= {r} < 40? {r_entre}")
print(f"0 <= {s} < 40? {s_entre}")
print(f"0 <= {t} < 40? {t_entre}")
print(f"0 <= {u} < 40? {u_entre}\n")

print(p_entre and q_entre and r_entre and s_entre and t_entre and u_entre)

0 <= 34.73 < 40? True
0 <= 1.67 < 40? True
0 <= 2.6 < 40? True
0 <= 0.14 < 40? True
0 <= 0.26 < 40? True
0 <= 7.88 < 40? True

True

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [9]:
p, q, r, s, t = df.iloc[-1, :]

print(f"{p} >= 10? {p >= 10}")
print(f"{q} >= 10? {q >= 10}")
print(f"{r} >= 10? {r >= 10}")
print(f"{s} >= 10? {s >= 10}")
print(f"{t} >= 10? {t >= 10}\n")

p >= 10 or q >= 10 or r >= 10 or s >= 10 or t >= 10

7.88 >= 10? False
2.15 >= 10? False
7.88 >= 10? False
2.15 >= 10? False
5.02 >= 10? False

False

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [10]:
df[(df > 5) & (df < 7)]

        0     1   2     3  Média
0     NaN   NaN NaN   NaN    NaN
1     NaN   NaN NaN  5.89    NaN
2     NaN   NaN NaN   NaN    NaN
3     NaN   NaN NaN   NaN    NaN
4     NaN  5.89 NaN   NaN    NaN
Média NaN   NaN NaN   NaN   5.02

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [11]:
df[(df <= 5) | (df > 7)]

           0     1      2     3  Média
0       2.60  2.80  34.73  0.07  10.05
1       0.14  1.61   1.67   NaN   2.33
2       0.26  0.37   2.60  2.80   1.51
3      34.73  0.07   0.14  1.61   9.14
4       1.67   NaN   0.26  0.37   2.05
Média   7.88  2.15   7.88  2.15    NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [12]:
import numpy as np

In [13]:
penultima_coluna = np.array(df.iloc[:, -2])
print(penultima_coluna)
print(2 <= penultima_coluna)
print(penultima_coluna <= 5)

[0.07 5.89 2.8  1.61 0.37 2.15]
[False  True  True False False  True]
[ True False  True  True  True  True]

In [14]:
ultima_coluna = np.array(df.loc[:, "Média"])
ultima_coluna

array([10.05,  2.33,  1.51,  9.14,  2.05,  5.02])

In [15]:
np.any([2 <= penultima_coluna, penultima_coluna <= 5])

True

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [16]:
print(f'''
    penultima_coluna >-1: {penultima_coluna}
    ultima_coluna >-1: {ultima_coluna}
    penultima_coluna < 12: {penultima_coluna}
    ultima_coluna < 12: {ultima_coluna}
''')

    penultima_coluna >-1: [0.07 5.89 2.8  1.61 0.37 2.15]
    ultima_coluna >-1: [10.05  2.33  1.51  9.14  2.05  5.02]
    penultima_coluna < 12: [0.07 5.89 2.8  1.61 0.37 2.15]
    ultima_coluna < 12: [10.05  2.33  1.51  9.14  2.05  5.02]

In [17]:
print(f'''
    penultima_coluna >-1: {penultima_coluna >-1}
    ultima_coluna >-1: {ultima_coluna >-1}
    penultima_coluna < 12: {penultima_coluna < 12}
    ultima_coluna < 12: {ultima_coluna < 12}
''')

    penultima_coluna >-1: [ True  True  True  True  True  True]
    ultima_coluna >-1: [ True  True  True  True  True  True]
    penultima_coluna < 12: [ True  True  True  True  True  True]
    ultima_coluna < 12: [ True  True  True  True  True  True]

In [18]:
np.all([
    penultima_coluna >-1,
    ultima_coluna >-1,
    penultima_coluna < 12,
    ultima_coluna < 12
])

True