# Exercício:

## Instancie um objeto da classe lista contendo 5.000 valores inteiros iniciando em 0. 
Quantos são pares e quantos são impares?

## 01 – Descreva o racional da sua resposta:

R.: Posso utilizar uma estrutura de repetição que é finalizada quando meu objeto tiver 5000 números. Com uma segunda estrutura, itero os itens no objeto. Divido cada um por 2 e obtenho o resto da divisão com o operador aritmético %. Quando o resultado for 0, isso significa que o número é par, quando for 1, é impar. Uso uma estrutura condicional para cada um dos valores e incremento um objeto inteiro para os pares e outro para os impares. Recupero com print.

## 02 – Desenhe o fluxograma da resposta:

<img src="./img/11-fluxograma_exercício1.png" width="1200" />

## 03 – Escreva o programa em Python:

In [5]:
lista_num = []
for conta in range(5_000):
    lista_num.append(conta)
len(lista_num)

5000

In [6]:
soma_par = 0
soma_impar = 0
for num in lista_num:
    if num % 2 == 0:
        soma_par += 1
    else:
        soma_impar += 1
print(f'Soma dos números pares: {soma_par:,.2f}'.replace(',', "_").replace('.', ",").replace('_', '.'))
print(f'Soma dos números ímpares: {soma_impar:,.2f}'.replace(',', "_").replace('.', ",").replace('_', '.'))

Soma dos números pares: 2.500,00
Soma dos números ímpares: 2.500,00

## 04 – Substitua a estrutura de repetição e responda novamente a pergunta anterior.

In [8]:
soma_par = 0
soma_impar = 0
conta = 0
while conta < len(lista_num):
    if lista_num[conta] % 2 == 0:
        soma_par += 1
    else:
        soma_impar += 1
    conta += 1
print(f'Soma dos números pares: {soma_par:,.2f}'.replace(',', "_").replace('.', ",").replace('_', '.'))
print(f'Soma dos números ímpares: {soma_impar:,.2f}'.replace(',', "_").replace('.', ",").replace('_', '.'))

Soma dos números pares: 2.500,00
Soma dos números ímpares: 2.500,00

In [9]:
import numpy as np

In [11]:
# Resposta alternativa sem o uso de loops
array_num = np.array(lista_num)
soma_par_array = len(array_num[array_num % 2 == 0])
soma_impar_array = len(array_num[array_num % 2 != 0])

print(f'Soma dos números pares (array): {soma_par_array:,.2f}'.replace(',', "_").replace('.', ",").replace('_', '.'))
print(f'Soma dos números ímpares (array): {soma_impar_array:,.2f}'.replace(',', "_").replace('.', ",").replace('_', '.'))

Soma dos números pares (array): 2.500,00
Soma dos números ímpares (array): 2.500,00

## Importe o .csv exportado na última aula e instancie um objeto da classe DataFrame.

Dos números de letras nos genes, quais são pares e quantos são impares?

## 05 – Descreva o racional da sua resposta:

R.: Importamos o módulo pandas. Importamos usando a função read_csv(), a DataFrame necessária. Iteramos com a estrutura de repetição os valores contidos na coluna solicitada. Divido cada um por 2 e obtenho o resto da divisão com o operador aritmético %. Quando o resultado for 0, isso significa que o número é par, quando for 1, é impar. Uso uma estrutura condicional para cada um dos valores e recupero com print.

## 06 – Desenhe o fluxograma da resposta:

<img src="./img/11-fluxograma_exercício6.png" width="1200" />

## 07 – Escreva o programa em Python:

In [12]:
import pandas as pd

In [14]:
df_genes = pd.read_csv("./data/df_genes_aula6exer7.csv", index_col="Unnamed: 0")
df_genes

         num_letras primeiras_duas_letras  num_a  contains_hu
isg15             5                    is      0        False
hur               3                    hu      0         True
ifna              4                    if      1        False
tnfa              4                    tn      1        False
atpsf1a           7                    at      2        False

In [17]:
for item in df_genes['num_letras']:
    if item%2 == 0:
        print(str(item) + " é par")
    else:
        print(str(item) + " é impar")

5 é impar
3 é impar
4 é par
4 é par
7 é impar

## 08 – Substitua a estrutura de repetição e responda novamente a pergunta anterior.

In [21]:
lista_par_impar_genes = [str(item) + " é par" if item % 2 == 0 else str(item) + " é impar" for item in df_genes['num_letras']]

conta = 0
while conta < len(lista_par_impar_genes):
    print(lista_par_impar_genes[conta])
    conta += 1

5 é impar
3 é impar
4 é par
4 é par
7 é impar

## 09 – Usando a coluna de presença de hu no nome do gene, itere os index deste objeto usando a função enumerate(). Estes index podem ser usados para imprimir cada um dos valores presentes na coluna dos dois primeiros caracteres dos nomes dos genes?

In [33]:
for index, item in enumerate(df_genes['contains_hu'].index):
    print(df_genes.iloc[index, 1])

is
hu
if
tn
at

## 10 – Selecione qualquer uma das instâncias contidas na DataFrame. É possível recuperar as chaves e os valores com ao menos 3 estruturas de repetição diferentes?

In [35]:
df_genes

         num_letras primeiras_duas_letras  num_a  contains_hu
isg15             5                    is      0        False
hur               3                    hu      0         True
ifna              4                    if      1        False
tnfa              4                    tn      1        False
atpsf1a           7                    at      2        False

In [42]:
valor_inst = 3
print(f"{df_genes.iloc[valor_inst, :].name}")
for index, item in enumerate(df_genes.iloc[valor_inst]):
    print(f"{index}- {item}")

tnfa
0- 4
1- tn
2- 1
3- False

In [44]:
print(f"{df_genes.iloc[valor_inst, :].name}")
for count in range(len(df_genes.iloc[valor_inst])):
    print(f"{count}- {df_genes.iloc[valor_inst, count]}")

tnfa
0- 4
1- tn
2- 1
3- False

In [50]:
print(f"{df_genes.iloc[valor_inst, :].name}")
count = 0
while count < len(df_genes.columns):
    print(f"{count}- {df_genes.iloc[valor_inst, count]}")
    count += 1

tnfa
0- 4
1- tn
2- 1
3- False

In [56]:
print(f"{df_genes.iloc[valor_inst, :].name}")
conta = 0
for item in df_genes.iloc[valor_inst, :]:
    print(conta, "-", item)
    conta += 1

tnfa
0 - 4
1 - tn
2 - 1
3 - False