# Importações

In [1]:
import os
import pandas as pd
import numpy as np

from util import utils as ut

In [2]:
# Verificando pasta de trabalho
os.listdir()

['alunos', 'aulas', 'data', 'exercicios', 'exercicios_resolvidos']

# Funções

In [3]:
def get_alunos(aluno: str) -> str:
    try:
        aluno_nome = aluno.split("https")[0]
        aluno_nome = aluno_nome[:-2]
    except:
        aluno_nome = aluno
    return aluno_nome

# Importando banco

In [4]:
# Lendo o arquivo CSV
df_exercicios = pd.read_csv("./alunos/data/relatorio_final_2026-05-02.csv")

# Extraindo os nomes dos alunos e renomeando as colunas
df_exercicios['alunos'] = [get_alunos(i) for i in df_exercicios['Alunos']]
df_exercicios.rename(columns={'Name': 'exercicio'}, inplace=True)

# Removendo colunas desnecessárias e reorganizando o DataFrame
df_exercicios.drop(columns=[
    "Acertos",
    "Total de questões",
    "Revisor",
    "Status",
    "Alunos",
], inplace=True)
df_exercicios.rename(columns={'Nota Final': 'notas'}, inplace=True)
df_exercicios = df_exercicios[["alunos", "exercicio", "notas"]]
df_exercicios.dropna(inplace=True)
df_exercicios.head()

                            alunos                    exercicio notas
0                Aline de Carvalho      09 - Operadores Logicos     0
1                Aline de Carvalho  08 - Operadores Relacionais     0
2                Aline de Carvalho  07 - Operadores Aritmeticos     0
3  Alessandra Conti Gomes de Souza              02 - Introducao     0
4                Aline de Carvalho     06 - Objetos Compostos 2     0

In [5]:
df_exercicios.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 391
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   alunos     392 non-null    object
 1   exercicio  392 non-null    object
 2   notas      392 non-null    object
dtypes: object(3)
memory usage: 12.2+ KB

In [6]:
# Editando a entrada "02 - Introducao " para "02 - Introducao"
index = df_exercicios[df_exercicios['exercicio'] == '02 - Introducao '].index
df_exercicios.loc[index, 'exercicio'] = '02 - Introducao'

# Editando a entrada "14-  Variaveis Quantitativas" para "14 - Variaveis Quantitativas"
index = df_exercicios[df_exercicios['exercicio'] == '14-  Variaveis Quantitativas'].index
df_exercicios.loc[index, 'exercicio'] = '14 - Variaveis Quantitativas'

# Editando a entrada "Natalia Zureck Xaviern" para "Natalia Zureck Xavier"
index = df_exercicios[df_exercicios['alunos'] == 'Natalia Zureck Xaviern'].index
df_exercicios.loc[index, 'alunos'] = 'Natalia Zureck Xavier'

# Editando a entrada "87,5" para 87.5
index = df_exercicios[df_exercicios['notas'] == "87,5"].index
df_exercicios.loc[index, 'notas'] = "87.5"

# Editando a entrada "190,0" para 90.0
index = df_exercicios[df_exercicios['notas'] == "190"].index
df_exercicios.loc[index, 'notas'] = 90

# Obtendo uma lista com os nomes dos exercícios 
exercicios = df_exercicios['exercicio'].value_counts().sort_values().index

# Obtendo uma lista com os nomes dos exercícios ordenados por número
exer_lista = []
for j in range(1, len(exercicios) + 5):
    for i in exercicios:
        if f"0{j}" == f"{i}".split(" - ")[0]:
            exer_lista.append(i)
        elif f"{j}" == f"{i}".split(" - ")[0]:
            exer_lista.append(i)
ut.printLis(exer_lista)

-------------
-=< Lista >=-
-------------
0 -> 02 - Introducao
1 -> 04 - ObjetosSimples
2 -> 05 - Objetos Compostos 1
3 -> 06 - Objetos Compostos 2
4 -> 07 - Operadores Aritmeticos
5 -> 08 - Operadores Relacionais
6 -> 09 - Operadores Logicos
7 -> 10 - Estruturas Condicionais
8 -> 11 - Estuturas de Repeticao
9 -> 12 - Rotinas
10 -> 13 - Variaveis Qualitativas
11 -> 14 - Variaveis Quantitativas
12 -> 15 - Medidas de Resumo 1
13 -> 16 - Medidas de Resumo 2

In [7]:
# Verificando as colunas da DataFrame
df_exercicios.head()

                            alunos                    exercicio notas
0                Aline de Carvalho      09 - Operadores Logicos     0
1                Aline de Carvalho  08 - Operadores Relacionais     0
2                Aline de Carvalho  07 - Operadores Aritmeticos     0
3  Alessandra Conti Gomes de Souza              02 - Introducao     0
4                Aline de Carvalho     06 - Objetos Compostos 2     0

In [8]:
# Modificando o tipo da coluna "nota" para float
df_exercicios['notas'] = df_exercicios['notas'].astype(float)
df_exercicios.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 391
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   alunos     392 non-null    object
 1   exercicio  392 non-null    object
 2   notas      392 non-null    float64
dtypes: float64(1), object(2)
memory usage: 20.4+ KB

In [9]:
df_notas = (
    df_exercicios
    .groupby("alunos")
    .notas
    .mean()
    .round(2)
    .to_frame()
    .reset_index()
)
df_notas

                                       alunos   notas
0             Alessandra Conti Gomes de Souza    0.00
1                           Aline de Carvalho    0.00
2                        Bianca Nichele Kusma  100.00
3                      Camilla Leitzke Toledo   79.57
4                         Camilla Maia Moraes   98.00
5                                Carolina Zem   96.64
6                     Emanuele Oliveira Jarno   81.43
7            Gabriela Maria da Costa Ferreira   88.39
8                     Gabriela Marino Koerich   98.57
9                          Hector Hugo Furini   99.93
10                   Isabel de Farias Ribeiro   98.57
11  Isadora Celine Rodrigues Carneiro Camargo   82.14
12                     Julia Cardoso da Silva   93.07
13                      Julia Weber Ferraboli   98.14
14              Livia Mendes Zacharow Pedroso   99.29
15                       Lucas Herrero Matias   69.14
16                              Mario Kujbida   99.64
17                           Mateus Marchetto   97.14
18                         Matheus Schipanski   97.14
19                      Natalia Zureck Xavier   96.86
20                 Natália Jeanegitz da Silva   98.50
21                       Nicholas Yuri Naufal   88.93
22             Paulo Henrique Moro dos Santos   68.93
23                         Rafael Uhlik Veiga   99.86
24                     Rodrigo Alexandre Lusa   96.07
25                      Sophia Pereira Ozorio   99.29
26                 Thais Agata Veiga Ferreira   97.14
27                              Yasmin Soares    0.00

In [10]:
df_exercicios['num_exercicios'] = df_exercicios['notas'] == 0.0
df_exercicios.head()

,alunos,exercicio,notas,num_exercicios
0,Aline de Carvalho,09 - Operadores Logicos,0.0,True
1,Aline de Carvalho,08 - Operadores Relacionais,0.0,True
2,Aline de Carvalho,07 - Operadores Aritmeticos,0.0,True
3,Alessandra Conti Gomes de Souza,02 - Introducao,0.0,True
4,Aline de Carvalho,06 - Objetos Compostos 2,0.0,True

In [11]:
# Instanciando uma DataFrame com os nomes dos alunos e o número de exercícios realizados
df_num_exercicios = (
    df_exercicios
    .groupby("alunos")
    .num_exercicios
    .sum()
    .to_frame()
    .reset_index()
    # .assign(num_exercicios=lambda x: x-14)
)
df_num_exercicios['num_exercicios'] = df_num_exercicios['num_exercicios'] - 14
df_num_exercicios['num_exercicios'] = df_num_exercicios['num_exercicios'] * -1
df_num_exercicios

                                       alunos  num_exercicios
0             Alessandra Conti Gomes de Souza               0
1                           Aline de Carvalho               0
2                        Bianca Nichele Kusma              14
3                      Camilla Leitzke Toledo              13
4                         Camilla Maia Moraes              14
5                                Carolina Zem              14
6                     Emanuele Oliveira Jarno              12
7            Gabriela Maria da Costa Ferreira              13
8                     Gabriela Marino Koerich              14
9                          Hector Hugo Furini              14
10                   Isabel de Farias Ribeiro              14
11  Isadora Celine Rodrigues Carneiro Camargo              12
12                     Julia Cardoso da Silva              14
13                      Julia Weber Ferraboli              14
14              Livia Mendes Zacharow Pedroso              14
15                       Lucas Herrero Matias              10
16                              Mario Kujbida              14
17                           Mateus Marchetto              14
18                         Matheus Schipanski              14
19                      Natalia Zureck Xavier              14
20                 Natália Jeanegitz da Silva              14
21                       Nicholas Yuri Naufal              13
22             Paulo Henrique Moro dos Santos              10
23                         Rafael Uhlik Veiga              14
24                     Rodrigo Alexandre Lusa              14
25                      Sophia Pereira Ozorio              14
26                 Thais Agata Veiga Ferreira              14
27                              Yasmin Soares               0

# Buscando e-mail dos alunos

In [12]:
# Carrega o arquivo de emails dos alunos
with open("./alunos/data/Email_Alunos.txt", "r") as f:
    data_email = f.readlines()
data_email

['2. Alessandra Conti Gomes de Souza - alessandra.conti@fiocruz.br\n',
 '3. Aline de Carvalho - acarvalho@tecpar.br \n',
 '4. Bianca Nichele Kusma - bkusma@aluno.fiocruz.br\n',
 '5. Camilla Leitzke Toledo - Camillatoledo453@gmail.com \n',
 '6. Camilla Maia Moraes - camillamaia36@gmail.com\n',
 '7. Carolina Zem - czem@aluno.fiocruz.br\n',
 '8. Emanuele Oliveira Jarno - ejarno@aluno.fiocruz.br\n',
 '9. Gabriela Maria da Costa Ferreira - gaferreira@aluno.fiocruz.br\n',
 '10. Gabriela Marino Koerich - gaby.koerich@hotmail.com \n',
 '11. Hector Hugo Furini -  hectorfurini@gmail.com\n',
 '12. Isabel de Farias Ribeiro - isabeldefariasribeiro@gmail.com\n',
 '13. Isadora Celine Rodrigues Carneiro Camargo - isacarneiro@hotmail.com.br\n',
 '14. Julia Cardoso da Silva - juliacardoso628@gmail.com\n',
 '15. Julia Weber Ferraboli - jferraboli@aluno.fiocruz.br\n',
 '16. Livia Mendes Zacharow Pedroso - lpedroso@aluno.fiocruz.br\n',
 '17. Lucas Herrero Matias - lherreromatias@gmail.com\n',
 '18. Mario Kujbida - mariokujbida@outlook.com\n',
 '19. Mateus Marchetto - mateusmarchetto2000@gmail.com\n',
 '20. Matheus Schipanski - matcow53@gmail.com\n',
 '21. Natália Jeanegitz da Silva - njeanegitz@gmail.com\n',
 '22. Natalia Zureck Xavier - nataliazureck.x@gmail.com\n',
 '23. Nicholas Yuri Naufal - nnaufal@aluno.fiocruz.br\n',
 '24. Paulo Henrique Moro dos Santos - p.moro@aluno.fiocruz.br\n',
 '25. Rafael Uhlik Veiga - rafaeluveiga@gmail.com\n',
 '26. Rodrigo Alexandre Lusa - lusarodrigo4@gmail.com\n',
 '27. Sophia Pereira Ozorio - sozorio@aluno.fiocruz.br\n',
 '28. Thais Agata Veiga Ferreira - tveiga@aluno.fiocruz.br\n',
 '29. Yasmin Soares - gaferreira@gmail.com']

In [13]:
# Instancando uma lista com os nomes dos alunos a partir do arquivo de emails
lista_alunos_email = [v[3:].strip().split(" - ") if k < 10 else v[4:].strip().split(" - ") for k, v in enumerate(data_email)]
lista_alunos_nomes = [i[0] for i in lista_alunos_email]
ut.printLis(lista_alunos_nomes)

-------------
-=< Lista >=-
-------------
0 -> Alessandra Conti Gomes de Souza
1 -> Aline de Carvalho
2 -> Bianca Nichele Kusma
3 -> Camilla Leitzke Toledo
4 -> Camilla Maia Moraes
5 -> Carolina Zem
6 -> Emanuele Oliveira Jarno
7 -> Gabriela Maria da Costa Ferreira
8 -> Gabriela Marino Koerich
9 -> Hector Hugo Furini
10 -> Isabel de Farias Ribeiro
11 -> Isadora Celine Rodrigues Carneiro Camargo
12 -> Julia Cardoso da Silva
13 -> Julia Weber Ferraboli
14 -> Livia Mendes Zacharow Pedroso
15 -> Lucas Herrero Matias
16 -> Mario Kujbida
17 -> Mateus Marchetto
18 -> Matheus Schipanski
19 -> Natália Jeanegitz da Silva
20 -> Natalia Zureck Xavier
21 -> Nicholas Yuri Naufal
22 -> Paulo Henrique Moro dos Santos
23 -> Rafael Uhlik Veiga
24 -> Rodrigo Alexandre Lusa
25 -> Sophia Pereira Ozorio
26 -> Thais Agata Veiga Ferreira
27 -> Yasmin Soares

In [14]:
# Instanciando uma lista com os emails dos alunos a partir do arquivo de emails
lista_alunos_email = [i[1] for i in lista_alunos_email]
ut.printLis(lista_alunos_email)

-------------
-=< Lista >=-
-------------
0 -> alessandra.conti@fiocruz.br
1 -> acarvalho@tecpar.br
2 -> bkusma@aluno.fiocruz.br
3 -> Camillatoledo453@gmail.com
4 -> camillamaia36@gmail.com
5 -> czem@aluno.fiocruz.br
6 -> ejarno@aluno.fiocruz.br
7 -> gaferreira@aluno.fiocruz.br
8 -> gaby.koerich@hotmail.com
9 ->  hectorfurini@gmail.com
10 -> isabeldefariasribeiro@gmail.com
11 -> isacarneiro@hotmail.com.br
12 -> juliacardoso628@gmail.com
13 -> jferraboli@aluno.fiocruz.br
14 -> lpedroso@aluno.fiocruz.br
15 -> lherreromatias@gmail.com
16 -> mariokujbida@outlook.com
17 -> mateusmarchetto2000@gmail.com
18 -> matcow53@gmail.com
19 -> njeanegitz@gmail.com
20 -> nataliazureck.x@gmail.com
21 -> nnaufal@aluno.fiocruz.br
22 -> p.moro@aluno.fiocruz.br
23 -> rafaeluveiga@gmail.com
24 -> lusarodrigo4@gmail.com
25 -> sozorio@aluno.fiocruz.br
26 -> tveiga@aluno.fiocruz.br
27 -> gaferreira@gmail.com

# Buscando os url dos alunos

In [15]:
# Instanciaando uma lista com os nomes dos alunos e os url dos GitHub
with open("./alunos/data/GitHub_Alunos.txt", "r") as f:
    data_git = f.readlines()
data_git = data_git[1:]
data_git

['2. Alessandra Conti Gomes de Souza - https://github.com/alecgsbr-web/Aula-Phyton\n',
 '3. Aline de Carvalho - https://github.com/aline-bio/python-basico.git\n',
 '4. Bianca Nichele Kusma - https://github.com/biancankusma/python_basico.git\n',
 '5. Camilla Leitzke Toledo - https://github.com/camilaltoledo0502-art/Entregas-de-atividades-aula-Python-.git\n',
 '6. Camilla Maia Moraes - https://github.com/camss36/Python_b-sico_Camilla_Maia.git\n',
 '7. Carolina Zem - https://github.com/zemsacional/Aulas_Python\n',
 '8. Emanuele Oliveira Jarno - https://github.com/emanuelejarno/Aula-de-mestrado\n',
 '9. Gabriela Maria da Costa Ferreira - https://github.com/GbrielaMaria/Python\n',
 '10. Gabriela Marino Koerich - https://github.com/GabrielaKoerich/Mestrado-Python-Basico\n',
 '11. Hector Hugo Furini - https://github.com/hector-furini/Disciplina-PBp-Python\n',
 '12. Isabel de Farias Ribeiro - https://github.com/isabeldfribeiro/Disciplina_python\n',
 '13. Isadora Celine Rodrigues Carneiro Camargo - https://github.com/isacarneiro/python_basic_2026\n',
 '14. Julia Cardoso da Silva - https://github.com/cardosojulias/Mestrado_python_julia\n',
 '15. Julia Weber Ferraboli - https://github.com/jwferraboli/aulagithub.git\n',
 '16. Livia Mendes Zacharow Pedroso - https://github.com/Livia-Zacharow/aulas_python_doutorado.git\n',
 '17. Lucas Herrero Matias - https://github.com/lherreromatias/Disciplina_python\n',
 '18. Mario Kujbida - https://github.com/Mario-Kujbida/Python-B-sico.git\n',
 '19. Mateus Marchetto - https://github.com/marchettom/Disciplina-Python\n',
 '20. Matheus Schipanski - https://github.com/matcow/Aula-Python\n',
 '21. Natália Jeanegitz da Silva - https://github.com/njeanegitz/aula-python.git\n',
 '22. Natalia Zureck Xavier - https://github.com/NataliaZureck/AulaPythonBasico.git\n',
 '23. Nicholas Yuri Naufal - https://github.com/nicholasynaufal/Disciplina_Python.git\n',
 '24. Paulo Henrique Moro dos Santos - https://github.com/paulo-moro/disciplina_python_doc\n',
 '25. Rafael Uhlik Veiga - https://github.com/R-Zurik/Projeto-Inicial-Teste\n',
 '26. Rodrigo Alexandre Lusa - https://github.com/Rodrigo-Lusa/aulas_python_mestrado.git\n',
 '27. Sophia Pereira Ozorio - https://github.com/SophiaOzorio/mestrado_python\n',
 '28. Thais Agata Veiga Ferreira - https://github.com/tveigaferreira-hue/phyton-.git\n',
 '29. Yasmin Soares - https://github.com/yasminsoares01/aulas-Phyton']

In [16]:
# Instancando uma lista com os nomes e os url do GitHub
lista_alunos_git = [v[3:].strip().split(" - ") if k < 10 else v[4:].strip().split(" - ") for k, v in enumerate(data_git)]
lista_alunos_git[:4]

[['Alessandra Conti Gomes de Souza',
  'https://github.com/alecgsbr-web/Aula-Phyton'],
 ['Aline de Carvalho', 'https://github.com/aline-bio/python-basico.git'],
 ['Bianca Nichele Kusma', 'https://github.com/biancankusma/python_basico.git'],
 ['Camilla Leitzke Toledo',
  'https://github.com/camilaltoledo0502-art/Entregas-de-atividades-aula-Python-.git']]

# Agrupando os dados

In [17]:
# Instanciando uma DataFrame com os nomes dos alunos e os url do GitHub
data = {
    "alunos": [i[0] for i in lista_alunos_git],
    "github": [i[1] for i in lista_alunos_git],
}
df_git = pd.DataFrame(data)
df_git.head()

,alunos,github
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...

In [18]:
# Instanciando uma DataFrame com os nomes dos alunos e os emails
data = {
    "alunos": lista_alunos_nomes,
    "email": lista_alunos_email,
}
df_mail = pd.DataFrame(data)
df_mail.head()

                            alunos                        email
0  Alessandra Conti Gomes de Souza  alessandra.conti@fiocruz.br
1                Aline de Carvalho          acarvalho@tecpar.br
2             Bianca Nichele Kusma      bkusma@aluno.fiocruz.br
3           Camilla Leitzke Toledo   Camillatoledo453@gmail.com
4              Camilla Maia Moraes      camillamaia36@gmail.com

In [19]:
df_identificador = df_git.merge(df_mail, on="alunos", how="left")
df_exercicios_nomes = df_identificador.merge(df_num_exercicios, on="alunos", how="left")
df_alunos = df_exercicios_nomes.merge(df_notas, on="alunos", how="left")

df_alunos

,alunos,github,email,num_exercicios,notas
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,alessandra.conti@fiocruz.br,0,0.00
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,0,0.00
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git,bkusma@aluno.fiocruz.br,14,100.00
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,13,79.57
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...,camillamaia36@gmail.com,14,98.00
5,Carolina Zem,https://github.com/zemsacional/Aulas_Python,czem@aluno.fiocruz.br,14,96.64
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,13,88.39
8,Gabriela Marino Koerich,https://github.com/GabrielaKoerich/Mestrado-Py...,gaby.koerich@hotmail.com,14,98.57
9,Hector Hugo Furini,https://github.com/hector-furini/Disciplina-PB...,hectorfurini@gmail.com,14,99.93
10,Isabel de Farias Ribeiro,https://github.com/isabeldfribeiro/Disciplina_...,isabeldefariasribeiro@gmail.com,14,98.57
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
12,Julia Cardoso da Silva,https://github.com/cardosojulias/Mestrado_pyth...,juliacardoso628@gmail.com,14,93.07
13,Julia Weber Ferraboli,https://github.com/jwferraboli/aulagithub.git,jferraboli@aluno.fiocruz.br,14,98.14
14,Livia Mendes Zacharow Pedroso,https://github.com/Livia-Zacharow/aulas_python...,lpedroso@aluno.fiocruz.br,14,99.29
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,10,69.14
16,Mario Kujbida,https://github.com/Mario-Kujbida/Python-B-sico...,mariokujbida@outlook.com,14,99.64
17,Mateus Marchetto,https://github.com/marchettom/Disciplina-Python,mateusmarchetto2000@gmail.com,14,97.14
18,Matheus Schipanski,https://github.com/matcow/Aula-Python,matcow53@gmail.com,14,97.14
19,Natália Jeanegitz da Silva,https://github.com/njeanegitz/aula-python.git,njeanegitz@gmail.com,14,98.50
20,Natalia Zureck Xavier,https://github.com/NataliaZureck/AulaPythonBas...,nataliazureck.x@gmail.com,14,96.86
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
23,Rafael Uhlik Veiga,https://github.com/R-Zurik/Projeto-Inicial-Teste,rafaeluveiga@gmail.com,14,99.86
24,Rodrigo Alexandre Lusa,https://github.com/Rodrigo-Lusa/aulas_python_m...,lusarodrigo4@gmail.com,14,96.07
25,Sophia Pereira Ozorio,https://github.com/SophiaOzorio/mestrado_python,sozorio@aluno.fiocruz.br,14,99.29
26,Thais Agata Veiga Ferreira,https://github.com/tveigaferreira-hue/phyton-.git,tveiga@aluno.fiocruz.br,14,97.14
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [20]:
df_alunos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28 entries, 0 to 27
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   alunos          28 non-null     object
 1   github          28 non-null     object
 2   email           28 non-null     object
 3   num_exercicios  28 non-null     int64
 4   notas           28 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.3+ KB

# Editando entradas pelo GitHub

In [21]:
coluna = 'num_exercicios'
df_alunos[df_alunos[coluna] != 14]

,alunos,github,email,num_exercicios,notas
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,alessandra.conti@fiocruz.br,0,0.00
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,0,0.00
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,13,79.57
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,13,88.39
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,10,69.14
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [22]:
index = 0
print(df_alunos.loc[index, 'alunos'])
df_alunos.loc[index, coluna] = 14
df_alunos[df_alunos[coluna] != 14]

Alessandra Conti Gomes de Souza

,alunos,github,email,num_exercicios,notas
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,0,0.00
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,13,79.57
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,13,88.39
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,10,69.14
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [23]:
index = 1
print(df_alunos.loc[index, 'alunos'])
df_alunos.loc[index, coluna] = 1
df_alunos[df_alunos[coluna] != 14]

Aline de Carvalho

,alunos,github,email,num_exercicios,notas
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,13,79.57
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,13,88.39
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,10,69.14
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [24]:
index = 3
print(df_alunos.loc[index, 'alunos'])
df_alunos.loc[index, coluna] = 14
df_alunos[df_alunos[coluna] != 14]

Camilla Leitzke Toledo

,alunos,github,email,num_exercicios,notas
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,13,88.39
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,10,69.14
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [25]:
index = 6
print(df_alunos.loc[index, 'alunos'])
df_alunos.loc[index, coluna] = 12
df_alunos[df_alunos[coluna] != 14]

Emanuele Oliveira Jarno

,alunos,github,email,num_exercicios,notas
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,13,88.39
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,10,69.14
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [26]:
index = 7
print(df_alunos.loc[index, 'alunos'])
df_alunos.loc[index, coluna] = 14
df_alunos[df_alunos[coluna] != 14]

Gabriela Maria da Costa Ferreira

,alunos,github,email,num_exercicios,notas
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,10,69.14
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [27]:
index = 11
print(df_alunos.loc[index, 'alunos'])
df_alunos.loc[index, coluna] = 12
df_alunos[df_alunos[coluna] != 14]

Isadora Celine Rodrigues Carneiro Camargo

,alunos,github,email,num_exercicios,notas
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,10,69.14
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [28]:
index = 15
print(df_alunos.loc[index, 'alunos'])
df_alunos.loc[index, coluna] = 12
df_alunos[df_alunos[coluna] != 14]

Lucas Herrero Matias

,alunos,github,email,num_exercicios,notas
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,12,69.14
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,13,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [29]:
index = 21
print(df_alunos.loc[index, 'alunos'])
df_alunos.loc[index, coluna] = 14
df_alunos[df_alunos[coluna] != 14]

Nicholas Yuri Naufal

,alunos,github,email,num_exercicios,notas
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,12,69.14
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [30]:
df_alunos.iloc[:, :5]

,alunos,github,email,num_exercicios,notas
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,alessandra.conti@fiocruz.br,14,0.00
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git,bkusma@aluno.fiocruz.br,14,100.00
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,14,79.57
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...,camillamaia36@gmail.com,14,98.00
5,Carolina Zem,https://github.com/zemsacional/Aulas_Python,czem@aluno.fiocruz.br,14,96.64
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,14,88.39
8,Gabriela Marino Koerich,https://github.com/GabrielaKoerich/Mestrado-Py...,gaby.koerich@hotmail.com,14,98.57
9,Hector Hugo Furini,https://github.com/hector-furini/Disciplina-PB...,hectorfurini@gmail.com,14,99.93
10,Isabel de Farias Ribeiro,https://github.com/isabeldfribeiro/Disciplina_...,isabeldefariasribeiro@gmail.com,14,98.57
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14
12,Julia Cardoso da Silva,https://github.com/cardosojulias/Mestrado_pyth...,juliacardoso628@gmail.com,14,93.07
13,Julia Weber Ferraboli,https://github.com/jwferraboli/aulagithub.git,jferraboli@aluno.fiocruz.br,14,98.14
14,Livia Mendes Zacharow Pedroso,https://github.com/Livia-Zacharow/aulas_python...,lpedroso@aluno.fiocruz.br,14,99.29
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,12,69.14
16,Mario Kujbida,https://github.com/Mario-Kujbida/Python-B-sico...,mariokujbida@outlook.com,14,99.64
17,Mateus Marchetto,https://github.com/marchettom/Disciplina-Python,mateusmarchetto2000@gmail.com,14,97.14
18,Matheus Schipanski,https://github.com/matcow/Aula-Python,matcow53@gmail.com,14,97.14
19,Natália Jeanegitz da Silva,https://github.com/njeanegitz/aula-python.git,njeanegitz@gmail.com,14,98.50
20,Natalia Zureck Xavier,https://github.com/NataliaZureck/AulaPythonBas...,nataliazureck.x@gmail.com,14,96.86
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,14,88.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93
23,Rafael Uhlik Veiga,https://github.com/R-Zurik/Projeto-Inicial-Teste,rafaeluveiga@gmail.com,14,99.86
24,Rodrigo Alexandre Lusa,https://github.com/Rodrigo-Lusa/aulas_python_m...,lusarodrigo4@gmail.com,14,96.07
25,Sophia Pereira Ozorio,https://github.com/SophiaOzorio/mestrado_python,sozorio@aluno.fiocruz.br,14,99.29
26,Thais Agata Veiga Ferreira,https://github.com/tveigaferreira-hue/phyton-.git,tveiga@aluno.fiocruz.br,14,97.14
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00

In [31]:
def atribuir_conceito(nota: float) -> str:
    '''
        Conceito A - Entre 90% e 100% (rendimento excelente);
        Conceito B - Entre 75% e 89% (rendimento bom);
        Conceito C - Entre 60% e 74% (rendimento regular);
        Conceito D - Inferior a 60% (rendimento insuficiente).
    '''
    if 90 <= nota <= 100:
        return "A"
    elif 75 <= nota <= 89:
        return "B"
    elif 60 <= nota <= 74:
        return "C"
    elif nota < 60:
        return "D"

In [32]:
for i in [100, 90, 89, 75, 74, 60, 59]:
    print(f"Nota: {i} - Conceito: {atribuir_conceito(i)}")

Nota: 100 - Conceito: A
Nota: 90 - Conceito: A
Nota: 89 - Conceito: B
Nota: 75 - Conceito: B
Nota: 74 - Conceito: C
Nota: 60 - Conceito: C
Nota: 59 - Conceito: D

In [33]:
df_alunos['conceito'] = df_alunos.apply(lambda x: "D" if x['num_exercicios'] < 11 else atribuir_conceito(x['notas']), axis=1)
df_alunos['frequencia'] = round((df_alunos['num_exercicios']/14)*100, 0)
df_alunos

,alunos,github,email,num_exercicios,notas,conceito,frequencia
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,alessandra.conti@fiocruz.br,14,0.00,D,100.0
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00,D,7.0
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git,bkusma@aluno.fiocruz.br,14,100.00,A,100.0
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,14,79.57,B,100.0
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...,camillamaia36@gmail.com,14,98.00,A,100.0
5,Carolina Zem,https://github.com/zemsacional/Aulas_Python,czem@aluno.fiocruz.br,14,96.64,A,100.0
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43,B,86.0
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,14,88.39,B,100.0
8,Gabriela Marino Koerich,https://github.com/GabrielaKoerich/Mestrado-Py...,gaby.koerich@hotmail.com,14,98.57,A,100.0
9,Hector Hugo Furini,https://github.com/hector-furini/Disciplina-PB...,hectorfurini@gmail.com,14,99.93,A,100.0
10,Isabel de Farias Ribeiro,https://github.com/isabeldfribeiro/Disciplina_...,isabeldefariasribeiro@gmail.com,14,98.57,A,100.0
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14,B,86.0
12,Julia Cardoso da Silva,https://github.com/cardosojulias/Mestrado_pyth...,juliacardoso628@gmail.com,14,93.07,A,100.0
13,Julia Weber Ferraboli,https://github.com/jwferraboli/aulagithub.git,jferraboli@aluno.fiocruz.br,14,98.14,A,100.0
14,Livia Mendes Zacharow Pedroso,https://github.com/Livia-Zacharow/aulas_python...,lpedroso@aluno.fiocruz.br,14,99.29,A,100.0
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,12,69.14,C,86.0
16,Mario Kujbida,https://github.com/Mario-Kujbida/Python-B-sico...,mariokujbida@outlook.com,14,99.64,A,100.0
17,Mateus Marchetto,https://github.com/marchettom/Disciplina-Python,mateusmarchetto2000@gmail.com,14,97.14,A,100.0
18,Matheus Schipanski,https://github.com/matcow/Aula-Python,matcow53@gmail.com,14,97.14,A,100.0
19,Natália Jeanegitz da Silva,https://github.com/njeanegitz/aula-python.git,njeanegitz@gmail.com,14,98.50,A,100.0
20,Natalia Zureck Xavier,https://github.com/NataliaZureck/AulaPythonBas...,nataliazureck.x@gmail.com,14,96.86,A,100.0
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,14,88.93,B,100.0
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93,D,71.0
23,Rafael Uhlik Veiga,https://github.com/R-Zurik/Projeto-Inicial-Teste,rafaeluveiga@gmail.com,14,99.86,A,100.0
24,Rodrigo Alexandre Lusa,https://github.com/Rodrigo-Lusa/aulas_python_m...,lusarodrigo4@gmail.com,14,96.07,A,100.0
25,Sophia Pereira Ozorio,https://github.com/SophiaOzorio/mestrado_python,sozorio@aluno.fiocruz.br,14,99.29,A,100.0
26,Thais Agata Veiga Ferreira,https://github.com/tveigaferreira-hue/phyton-.git,tveiga@aluno.fiocruz.br,14,97.14,A,100.0
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00,D,0.0

# Inserindo Nota/Exercício

In [34]:
for i in exer_lista:
    df_alunos[i] = np.nan
df_alunos.head()

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,alessandra.conti@fiocruz.br,14,0.00,D,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00,D,7.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git,bkusma@aluno.fiocruz.br,14,100.00,A,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,14,79.57,B,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...,camillamaia36@gmail.com,14,98.00,A,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df_alunos.tail()

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
23,Rafael Uhlik Veiga,https://github.com/R-Zurik/Projeto-Inicial-Teste,rafaeluveiga@gmail.com,14,99.86,A,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Rodrigo Alexandre Lusa,https://github.com/Rodrigo-Lusa/aulas_python_m...,lusarodrigo4@gmail.com,14,96.07,A,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Sophia Pereira Ozorio,https://github.com/SophiaOzorio/mestrado_python,sozorio@aluno.fiocruz.br,14,99.29,A,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Thais Agata Veiga Ferreira,https://github.com/tveigaferreira-hue/phyton-.git,tveiga@aluno.fiocruz.br,14,97.14,A,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00,D,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df_exercicios.head()

,alunos,exercicio,notas,num_exercicios
0,Aline de Carvalho,09 - Operadores Logicos,0.0,True
1,Aline de Carvalho,08 - Operadores Relacionais,0.0,True
2,Aline de Carvalho,07 - Operadores Aritmeticos,0.0,True
3,Alessandra Conti Gomes de Souza,02 - Introducao,0.0,True
4,Aline de Carvalho,06 - Objetos Compostos 2,0.0,True

In [37]:
def atualizar_notas(
            aluno: int,
            notas_final: list[int]
    ) -> None:
    '''
        Função para atualizar as notas dos exercícios de um aluno específico.
                Args:
                        aluno (int): Índice do aluno na DataFrame df_alunos.
                        notas_final (list[int]): Lista com as notas finais dos
                        exercícios do aluno.
                Retorna:
                        None
    '''
#     Buscando index dos exercicios do aluno específico
    index = (
        df_exercicios[df_exercicios['alunos'] == df_alunos['alunos'][aluno]]
        .sort_values(by="exercicio")
        .index
    )

#     Atualizando as notas dos exercícios do aluno específico
    df_exercicios.loc[index, 'notas'] = notas_final

#     Instanciando lista de index das colunas de exercícios
    colunas = [7,8,9,10,11,12,13][::-1]
    colunas += [14,15,16,17,18,19,20][::-1]

#     Atualizando as notas dos exercícios do aluno específico na df_alunos
    df_alunos.iloc[aluno, 7:] = df_exercicios.loc[index, 'notas'].values

#     Visualizando as notas dos exercícios do aluno específico
    display(df_alunos[df_alunos['alunos'] == df_alunos['alunos'][aluno]])
    return None

# Editando notas

In [38]:
df_alunos['alunos']

0               Alessandra Conti Gomes de Souza
1                             Aline de Carvalho
2                          Bianca Nichele Kusma
3                        Camilla Leitzke Toledo
4                           Camilla Maia Moraes
5                                  Carolina Zem
6                       Emanuele Oliveira Jarno
7              Gabriela Maria da Costa Ferreira
8                       Gabriela Marino Koerich
9                            Hector Hugo Furini
10                     Isabel de Farias Ribeiro
11    Isadora Celine Rodrigues Carneiro Camargo
12                       Julia Cardoso da Silva
13                        Julia Weber Ferraboli
14                Livia Mendes Zacharow Pedroso
15                         Lucas Herrero Matias
16                                Mario Kujbida
17                             Mateus Marchetto
18                           Matheus Schipanski
19                   Natália Jeanegitz da Silva
20                        Natalia Zureck Xavier
21                         Nicholas Yuri Naufal
22               Paulo Henrique Moro dos Santos
23                           Rafael Uhlik Veiga
24                       Rodrigo Alexandre Lusa
25                        Sophia Pereira Ozorio
26                   Thais Agata Veiga Ferreira
27                                Yasmin Soares
Name: alunos, dtype: object

In [39]:
notas_finais = np.array([
# Alessandra Conti Gomes de Souza
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13],
# Aline de Carvalho
    [0,10,20,30,40,50,60,70,80,90,100,110,120,130],
# Bianca Nichele Kusma
    [0]*14,
# Camilla Leitzke Toledo
    [1]*14,
# Camilla Maia Moraes
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13],
# Carolina Zem
    [0,10,20,30,40,50,60,70,80,90,100,110,120,130],
# Emanuele Oliveira Jarno
    [0]*14,
# Gabriela Maria da Costa Ferreira
    [1]*14,
# Gabriela Marino Koerich
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13],
# Hector Hugo Furini
    [0,10,20,30,40,50,60,70,80,90,100,110,120,130],
# Isabel de Farias Ribeiro
    [0]*14,
# Isadora Celine Rodrigues Carneiro Camargo
    [1]*14,
# Julia Cardoso da Silva
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13],
# Julia Weber Ferraboli
    [0,10,20,30,40,50,60,70,80,90,100,110,120,130],
# Livia Mendes Zacharow Pedroso
    [0]*14,
# Lucas Herrero Matias
    [1]*14,
# Mario Kujbida
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13],
# Mateus Marchetto
    [0,10,20,30,40,50,60,70,80,90,100,110,120,130],
# Matheus Schipanski
    [0]*14,
# Natália Jeanegitz da Silva
    [1]*14,
# Natalia Zureck Xavier
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13],
# Nicholas Yuri Naufal
    [0,10,20,30,40,50,60,70,80,90,100,110,120,130],
# Paulo Henrique Moro dos Santos
    [0]*14,
# Rafael Uhlik Veiga
    [1]*14,
# Rodrigo Alexandre Lusa
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13],
# Sophia Pereira Ozorio
    [0,10,20,30,40,50,60,70,80,90,100,110,120,130],
# Thais Agata Veiga Ferreira
    [0]*14,
# Yasmin Soares
    [0]*14,
])
notas_finais.shape

(28, 14)

In [40]:
c = 0
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,alessandra.conti@fiocruz.br,14,0.0,D,100.0,0.0,1.0,2.0,...,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0

In [41]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.0,D,7.0,0.0,10.0,20.0,...,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0,120.0,130.0

In [42]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git,bkusma@aluno.fiocruz.br,14,100.0,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,14,79.57,B,100.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [44]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...,camillamaia36@gmail.com,14,98.0,A,100.0,0.0,1.0,2.0,...,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0

In [45]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
5,Carolina Zem,https://github.com/zemsacional/Aulas_Python,czem@aluno.fiocruz.br,14,96.64,A,100.0,0.0,10.0,20.0,...,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0,120.0,130.0

In [46]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43,B,86.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,14,88.39,B,100.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [48]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
8,Gabriela Marino Koerich,https://github.com/GabrielaKoerich/Mestrado-Py...,gaby.koerich@hotmail.com,14,98.57,A,100.0,0.0,1.0,2.0,...,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0

In [49]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
9,Hector Hugo Furini,https://github.com/hector-furini/Disciplina-PB...,hectorfurini@gmail.com,14,99.93,A,100.0,0.0,10.0,20.0,...,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0,120.0,130.0

In [50]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
10,Isabel de Farias Ribeiro,https://github.com/isabeldfribeiro/Disciplina_...,isabeldefariasribeiro@gmail.com,14,98.57,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14,B,86.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [52]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
12,Julia Cardoso da Silva,https://github.com/cardosojulias/Mestrado_pyth...,juliacardoso628@gmail.com,14,93.07,A,100.0,0.0,1.0,2.0,...,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0

In [53]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
13,Julia Weber Ferraboli,https://github.com/jwferraboli/aulagithub.git,jferraboli@aluno.fiocruz.br,14,98.14,A,100.0,0.0,10.0,20.0,...,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0,120.0,130.0

In [54]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
14,Livia Mendes Zacharow Pedroso,https://github.com/Livia-Zacharow/aulas_python...,lpedroso@aluno.fiocruz.br,14,99.29,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,12,69.14,C,86.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [56]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
16,Mario Kujbida,https://github.com/Mario-Kujbida/Python-B-sico...,mariokujbida@outlook.com,14,99.64,A,100.0,0.0,1.0,2.0,...,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0

In [57]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
17,Mateus Marchetto,https://github.com/marchettom/Disciplina-Python,mateusmarchetto2000@gmail.com,14,97.14,A,100.0,0.0,10.0,20.0,...,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0,120.0,130.0

In [58]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
18,Matheus Schipanski,https://github.com/matcow/Aula-Python,matcow53@gmail.com,14,97.14,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
19,Natália Jeanegitz da Silva,https://github.com/njeanegitz/aula-python.git,njeanegitz@gmail.com,14,98.5,A,100.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [60]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
20,Natalia Zureck Xavier,https://github.com/NataliaZureck/AulaPythonBas...,nataliazureck.x@gmail.com,14,96.86,A,100.0,0.0,1.0,2.0,...,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0

In [61]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,14,88.93,B,100.0,0.0,10.0,20.0,...,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0,120.0,130.0

In [62]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93,D,71.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [63]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
23,Rafael Uhlik Veiga,https://github.com/R-Zurik/Projeto-Inicial-Teste,rafaeluveiga@gmail.com,14,99.86,A,100.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [64]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
24,Rodrigo Alexandre Lusa,https://github.com/Rodrigo-Lusa/aulas_python_m...,lusarodrigo4@gmail.com,14,96.07,A,100.0,0.0,1.0,2.0,...,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0

In [65]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
25,Sophia Pereira Ozorio,https://github.com/SophiaOzorio/mestrado_python,sozorio@aluno.fiocruz.br,14,99.29,A,100.0,0.0,10.0,20.0,...,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0,120.0,130.0

In [66]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
26,Thais Agata Veiga Ferreira,https://github.com/tveigaferreira-hue/phyton-.git,tveiga@aluno.fiocruz.br,14,97.14,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
c += 1
atualizar_notas(
            aluno=c,
            notas_final=notas_finais[c]
)

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.0,D,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Valores finais

In [68]:
df_alunos['notas_revisadas'] = df_alunos.iloc[:, 7:].mean(axis=1)
df_alunos['conceito_revisado'] = df_alunos['notas_revisadas'].apply(atribuir_conceito)
df_alunos['difer_final'] = df_alunos['notas_revisadas'] - df_alunos['notas']
df_alunos

,alunos,github,email,num_exercicios,notas,conceito,frequencia,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,...,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14 - Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2,notas_revisadas,conceito_revisado,difer_final
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,alessandra.conti@fiocruz.br,14,0.00,D,100.0,0.0,1.0,2.0,...,7.0,8.0,9.0,10.0,11.0,12.0,13.0,6.5,D,6.50
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,acarvalho@tecpar.br,1,0.00,D,7.0,0.0,10.0,20.0,...,70.0,80.0,90.0,100.0,110.0,120.0,130.0,65.0,C,65.00
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git,bkusma@aluno.fiocruz.br,14,100.00,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,D,-100.00
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,Camillatoledo453@gmail.com,14,79.57,B,100.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,D,-78.57
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...,camillamaia36@gmail.com,14,98.00,A,100.0,0.0,1.0,2.0,...,7.0,8.0,9.0,10.0,11.0,12.0,13.0,6.5,D,-91.50
5,Carolina Zem,https://github.com/zemsacional/Aulas_Python,czem@aluno.fiocruz.br,14,96.64,A,100.0,0.0,10.0,20.0,...,70.0,80.0,90.0,100.0,110.0,120.0,130.0,65.0,C,-31.64
6,Emanuele Oliveira Jarno,https://github.com/emanuelejarno/Aula-de-mestrado,ejarno@aluno.fiocruz.br,12,81.43,B,86.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,D,-81.43
7,Gabriela Maria da Costa Ferreira,https://github.com/GbrielaMaria/Python,gaferreira@aluno.fiocruz.br,14,88.39,B,100.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,D,-87.39
8,Gabriela Marino Koerich,https://github.com/GabrielaKoerich/Mestrado-Py...,gaby.koerich@hotmail.com,14,98.57,A,100.0,0.0,1.0,2.0,...,7.0,8.0,9.0,10.0,11.0,12.0,13.0,6.5,D,-92.07
9,Hector Hugo Furini,https://github.com/hector-furini/Disciplina-PB...,hectorfurini@gmail.com,14,99.93,A,100.0,0.0,10.0,20.0,...,70.0,80.0,90.0,100.0,110.0,120.0,130.0,65.0,C,-34.93
10,Isabel de Farias Ribeiro,https://github.com/isabeldfribeiro/Disciplina_...,isabeldefariasribeiro@gmail.com,14,98.57,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,D,-98.57
11,Isadora Celine Rodrigues Carneiro Camargo,https://github.com/isacarneiro/python_basic_2026,isacarneiro@hotmail.com.br,12,82.14,B,86.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,D,-81.14
12,Julia Cardoso da Silva,https://github.com/cardosojulias/Mestrado_pyth...,juliacardoso628@gmail.com,14,93.07,A,100.0,0.0,1.0,2.0,...,7.0,8.0,9.0,10.0,11.0,12.0,13.0,6.5,D,-86.57
13,Julia Weber Ferraboli,https://github.com/jwferraboli/aulagithub.git,jferraboli@aluno.fiocruz.br,14,98.14,A,100.0,0.0,10.0,20.0,...,70.0,80.0,90.0,100.0,110.0,120.0,130.0,65.0,C,-33.14
14,Livia Mendes Zacharow Pedroso,https://github.com/Livia-Zacharow/aulas_python...,lpedroso@aluno.fiocruz.br,14,99.29,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,D,-99.29
15,Lucas Herrero Matias,https://github.com/lherreromatias/Disciplina_p...,lherreromatias@gmail.com,12,69.14,C,86.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,D,-68.14
16,Mario Kujbida,https://github.com/Mario-Kujbida/Python-B-sico...,mariokujbida@outlook.com,14,99.64,A,100.0,0.0,1.0,2.0,...,7.0,8.0,9.0,10.0,11.0,12.0,13.0,6.5,D,-93.14
17,Mateus Marchetto,https://github.com/marchettom/Disciplina-Python,mateusmarchetto2000@gmail.com,14,97.14,A,100.0,0.0,10.0,20.0,...,70.0,80.0,90.0,100.0,110.0,120.0,130.0,65.0,C,-32.14
18,Matheus Schipanski,https://github.com/matcow/Aula-Python,matcow53@gmail.com,14,97.14,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,D,-97.14
19,Natália Jeanegitz da Silva,https://github.com/njeanegitz/aula-python.git,njeanegitz@gmail.com,14,98.50,A,100.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,D,-97.50
20,Natalia Zureck Xavier,https://github.com/NataliaZureck/AulaPythonBas...,nataliazureck.x@gmail.com,14,96.86,A,100.0,0.0,1.0,2.0,...,7.0,8.0,9.0,10.0,11.0,12.0,13.0,6.5,D,-90.36
21,Nicholas Yuri Naufal,https://github.com/nicholasynaufal/Disciplina_...,nnaufal@aluno.fiocruz.br,14,88.93,B,100.0,0.0,10.0,20.0,...,70.0,80.0,90.0,100.0,110.0,120.0,130.0,65.0,C,-23.93
22,Paulo Henrique Moro dos Santos,https://github.com/paulo-moro/disciplina_pytho...,p.moro@aluno.fiocruz.br,10,68.93,D,71.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,D,-68.93
23,Rafael Uhlik Veiga,https://github.com/R-Zurik/Projeto-Inicial-Teste,rafaeluveiga@gmail.com,14,99.86,A,100.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,D,-98.86
24,Rodrigo Alexandre Lusa,https://github.com/Rodrigo-Lusa/aulas_python_m...,lusarodrigo4@gmail.com,14,96.07,A,100.0,0.0,1.0,2.0,...,7.0,8.0,9.0,10.0,11.0,12.0,13.0,6.5,D,-89.57
25,Sophia Pereira Ozorio,https://github.com/SophiaOzorio/mestrado_python,sozorio@aluno.fiocruz.br,14,99.29,A,100.0,0.0,10.0,20.0,...,70.0,80.0,90.0,100.0,110.0,120.0,130.0,65.0,C,-34.29
26,Thais Agata Veiga Ferreira,https://github.com/tveigaferreira-hue/phyton-.git,tveiga@aluno.fiocruz.br,14,97.14,A,100.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,D,-97.14
27,Yasmin Soares,https://github.com/yasminsoares01/aulas-Phyton,gaferreira@gmail.com,0,0.00,D,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,D,0.00