In [1]:
import os
import pandas as pd
import numpy as np
import requests

In [2]:
os.listdir()

['alunos', 'aulas', 'data', 'exercicios', 'exercicios_resolvidos']

In [3]:
df_exercicios = pd.read_csv("./alunos/data/exercicios_python_basico.csv")
df_exercicios.head()

,Name,Alunos,Nota Final,Acertos,Total de questões,Status,Revisor
0,02 - Introducao,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN
1,16 - Medidas de Resumo 2,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN
2,15 - Medidas de Resumo 1,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN
3,14- Variaveis Quantitativas,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN
4,13 - Variaveis Qualitativas,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN

In [4]:
exercicios = df_exercicios['Name'].value_counts().sort_index().index
exercicios

Index(['02 - Introducao', '02 - Introducao ', '04 - ObjetosSimples',
       '05 - Objetos Compostos 1', '06 - Objetos Compostos 2',
       '07 - Operadores Aritmeticos', '08 - Operadores Relacionais',
       '09 - Operadores Logicos', '10 - Estruturas Condicionais',
       '11 - Estuturas de Repeticao', '12 - Rotinas',
       '13 - Variaveis Qualitativas', '14-  Variaveis Quantitativas',
       '15 - Medidas de Resumo 1', '16 - Medidas de Resumo 2'],
      dtype='object')

In [5]:
exercicios[1]

'02 - Introducao '

In [6]:
c = 0
df_exercicios[df_exercicios['Name'] == exercicios[c]]

,Name,Alunos,Nota Final,Acertos,Total de questões,Status,Revisor
0,02 - Introducao,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN
20,02 - Introducao,Aline de Carvalho (https://www.notion.so/Aline...,0,NaN,NaN,A fazer,NaN
28,02 - Introducao,Bianca Nichele Kusma (https://www.notion.so/Bi...,100,4,4.0,Revisado,Jessica
56,02 - Introducao,Camilla Maia Moraes (https://www.notion.so/Cam...,100,4,4.0,Revisado,Jessica
74,02 - Introducao,Carolina Zem (https://www.notion.so/Carolina-Z...,100,4,4.0,Revisado,Jessica
84,02 - Introducao,Emanuele Oliveira Jarno (https://www.notion.so...,80,"3,2",4.0,Informação faltando (aluno precisa verificar),Jessica
98,02 - Introducao,Gabriela Maria da Costa Ferreira (https://www....,"87,5","3,5",4.0,Revisado,Jessica
112,02 - Introducao,Gabriela Marino Koerich (https://www.notion.so...,100,4,4.0,Revisado,Jessica
126,02 - Introducao,Hector Hugo Furini (https://www.notion.so/Hect...,100,4,4.0,Revisado,Jessica
140,02 - Introducao,Isabel de Farias Ribeiro (https://www.notion.s...,100,4,4.0,Revisado,Jessica
154,02 - Introducao,Isadora Celine Rodrigues Carneiro Camargo (htt...,80,"3,2",4.0,Revisado,Jessica
169,02 - Introducao,Julia Cardoso da Silva (https://www.notion.so/...,100,4,4.0,Revisado,Jessica
182,02 - Introducao,Julia Weber Ferraboli (https://www.notion.so/J...,98,"3,92",4.0,Revisado,Jessica
196,02 - Introducao,Livia Mendes Zacharow Pedroso (https://www.not...,100,4,4.0,Revisado,Felipe
210,02 - Introducao,Lucas Herrero Matias (https://www.notion.so/Lu...,100,4,4.0,Revisado,Jessica
224,02 - Introducao,Mario Kujbida (https://www.notion.so/Mario-Kuj...,95,"3,8",4.0,Quero que corrijam novamente,Jessica
251,02 - Introducao,Mateus Marchetto (https://www.notion.so/Mateus...,100,4,4.0,Revisado,Jessica
252,02 - Introducao,Matheus Schipanski (https://www.notion.so/Math...,100,4,4.0,Revisado,Jessica
266,02 - Introducao,Natália Jeanegitz da Silva (https://www.notion...,100,4,4.0,Revisado,Jessica
280,02 - Introducao,Natalia Zureck Xaviern (https://www.notion.so/...,100,4,4.0,Revisado,Jessica
305,02 - Introducao,Nicholas Yuri Naufal (https://www.notion.so/Ni...,0,0,4.0,Quero que corrijam novamente,Jessica
308,02 - Introducao,Paulo Henrique Moro dos Santos (https://www.no...,100,4,4.0,Revisado,Jessica
322,02 - Introducao,Rafael Uhlik Veiga (https://www.notion.so/Rafa...,100,4,4.0,Revisado,Jessica
336,02 - Introducao,Rodrigo Alexandre Lusa (https://www.notion.so/...,100,4,4.0,Revisado,Jessica
359,02 - Introducao,Sophia Pereira Ozorio (https://www.notion.so/S...,100,4,4.0,Revisado,Jessica
364,02 - Introducao,Thais Agata Veiga Ferreira (https://www.notion...,100,4,4.0,Revisado,Jessica
378,02 - Introducao,Yasmin Soares (https://www.notion.so/Yasmin-So...,0,NaN,NaN,A fazer,NaN

In [7]:
def get_alunos(aluno: str) -> str:
    try:
        aluno_nome = aluno.split("https")[0]
        aluno_nome = aluno_nome[:-2]
    except:
        aluno_nome = aluno
    return aluno_nome

In [8]:
df_exercicios['alunos'] = [get_alunos(i) for i in df_exercicios['Alunos']]
df_exercicios.head()

,Name,Alunos,Nota Final,Acertos,Total de questões,Status,Revisor,alunos
0,02 - Introducao,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN,Alessandra Conti Gomes de Souza
1,16 - Medidas de Resumo 2,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN,Alessandra Conti Gomes de Souza
2,15 - Medidas de Resumo 1,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN,Alessandra Conti Gomes de Souza
3,14- Variaveis Quantitativas,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN,Alessandra Conti Gomes de Souza
4,13 - Variaveis Qualitativas,Alessandra Conti Gomes de Souza (https://www.n...,0,NaN,NaN,A fazer,NaN,Alessandra Conti Gomes de Souza

In [9]:
df_exercicios.drop(columns=['Alunos', 'Status', 'Revisor', 'Total de questões', 'Acertos'], inplace=True)
df_exercicios.rename(columns={'Name': 'exercicio'}, inplace=True)
df_exercicios.head()

                      exercicio Nota Final                           alunos
0               02 - Introducao          0  Alessandra Conti Gomes de Souza
1      16 - Medidas de Resumo 2          0  Alessandra Conti Gomes de Souza
2      15 - Medidas de Resumo 1          0  Alessandra Conti Gomes de Souza
3  14-  Variaveis Quantitativas          0  Alessandra Conti Gomes de Souza
4   13 - Variaveis Qualitativas          0  Alessandra Conti Gomes de Souza

In [10]:
# exercicios = [i[:-6] for i in os.listdir("exercicios_resolvidos") if i.endswith(".ipynb")]
exercicios

Index(['02 - Introducao', '02 - Introducao ', '04 - ObjetosSimples',
       '05 - Objetos Compostos 1', '06 - Objetos Compostos 2',
       '07 - Operadores Aritmeticos', '08 - Operadores Relacionais',
       '09 - Operadores Logicos', '10 - Estruturas Condicionais',
       '11 - Estuturas de Repeticao', '12 - Rotinas',
       '13 - Variaveis Qualitativas', '14-  Variaveis Quantitativas',
       '15 - Medidas de Resumo 1', '16 - Medidas de Resumo 2'],
      dtype='object')

In [11]:
with open("./alunos/data/Email_Alunos.txt", "r") as f:
    data_email = f.readlines()
data_email = data_email[1:]
data_email

['3. Aline de Carvalho - \n',
 '4. Bianca Nichele Kusma - bkusma@aluno.fiocruz.br\n',
 '5. Camilla Leitzke Toledo - Camillatoledo453@gmail.com \n',
 '6. Camilla Maia Moraes - \n',
 '7. Carolina Zem - \n',
 '8. Emanuele Oliveira Jarno - \n',
 '9. Gabriela Maria da Costa Ferreira - gaferreira@aluno.fiocruz.br\n',
 '10. Gabriela Marino Koerich - \n',
 '11. Hector Hugo Furini -  hectorfurini@gmail.com\n',
 '12. Isabel de Farias Ribeiro - isabeldefariasribeiro@gmail.com\n',
 '13. Isadora Celine Rodrigues Carneiro Camargo - isacarneiro@hotmail.com.br\n',
 '14. Julia Cardoso da Silva - juliacardoso628@gmail.com\n',
 '15. Julia Weber Ferraboli - jferraboli@aluno.fiocruz.br\n',
 '16. Livia Mendes Zacharow Pedroso - lpedroso@aluno.fiocruz.br\n',
 '17. Lucas Herrero Matias - \n',
 '18. Mario Kujbida - mariokujbida@outlook.com\n',
 '19. Mateus Marchetto - mateusmarchetto2000@gmail.com\n',
 '20. Matheus Schipanski - \n',
 '21. Natália Jeanegitz da Silva - njeanegitz@gmail.com\n',
 '22. Natalia Zureck Xavier - nataliazureck.x@gmail.com\n',
 '23. Nicholas Yuri Naufal - nnaufal@aluno.fiocruz.br\n',
 '24. Paulo Henrique Moro dos Santos - \n',
 '25. Rafael Uhlik Veiga - rafaeluveiga@gmail.com\n',
 '26. Rodrigo Alexandre Lusa - lusarodrigo4@gmail.com\n',
 '27. Sophia Pereira Ozorio - sozorio@aluno.fiocruz.br\n',
 '28. Thais Agata Veiga Ferreira - tveiga@aluno.fiocruz.br\n',
 '29. Yasmin Soares -']

In [12]:
with open("./alunos/data/GitHub_Alunos.txt", "r") as f:
    data_git = f.readlines()
data_git = data_git[1:]
data_git

['2. Alessandra Conti Gomes de Souza - https://github.com/alecgsbr-web/Aula-Phyton\n',
 '3. Aline de Carvalho - https://github.com/aline-bio/python-basico.git\n',
 '4. Bianca Nichele Kusma - https://github.com/biancankusma/python_basico.git\n',
 '5. Camilla Leitzke Toledo - https://github.com/camilaltoledo0502-art/Entregas-de-atividades-aula-Python-.git\n',
 '6. Camilla Maia Moraes - https://github.com/camss36/Python_b-sico_Camilla_Maia.git\n',
 '7. Carolina Zem - https://github.com/zemsacional/Aulas_Python\n',
 '8. Emanuele Oliveira Jarno - https://github.com/emanuelejarno/Aula-de-mestrado\n',
 '9. Gabriela Maria da Costa Ferreira - https://github.com/GbrielaMaria/Python\n',
 '10. Gabriela Marino Koerich - https://github.com/GabrielaKoerich/Mestrado-Python-Basico\n',
 '11. Hector Hugo Furini - https://github.com/hector-furini/Disciplina-PBp-Python\n',
 '12. Isabel de Farias Ribeiro - https://github.com/isabeldfribeiro/Disciplina_python\n',
 '13. Isadora Celine Rodrigues Carneiro Camargo - https://github.com/isacarneiro/python_basic_2026\n',
 '14. Julia Cardoso da Silva - https://github.com/cardosojulias/Mestrado_python_julia\n',
 '15. Julia Weber Ferraboli - https://github.com/jwferraboli/aulagithub.git\n',
 '16. Livia Mendes Zacharow Pedroso - https://github.com/Livia-Zacharow/aulas_python_doutorado.git\n',
 '17. Lucas Herrero Matias - https://github.com/lherreromatias/Disciplina_pyton\n',
 '18. Mario Kujbida - https://github.com/Mario-Kujbida/Python-B-sico.git\n',
 '19. Mateus Marchetto - https://github.com/marchettom/Disciplina-Python\n',
 '20. Matheus Schipanski - https://github.com/matcow/Aula-Python\n',
 '21. Natália Jeanegitz da Silva - https://github.com/njeanegitz/aula-python.git\n',
 '22. Natalia Zureck Xavier - https://github.com/NataliaZureck/AulaPythonBasico.git\n',
 '23. Nicholas Yuri Naufal - https://github.com/nicholasynaufal/Disciplina_Python.git\n',
 '24. Paulo Henrique Moro dos Santos - https://github.com/paulo-moro/disciplina_python_doc\n',
 '25. Rafael Uhlik Veiga - https://github.com/R-Zurik/Projeto-Inicial-Teste\n',
 '26. Rodrigo Alexandre Lusa - https://github.com/Rodrigo-Lusa/aulas_python_mestrado.git\n',
 '27. Sophia Pereira Ozorio - https://github.com/SophiaOzorio/mestrado_python\n',
 '28. Thais Agata Veiga Ferreira - https://github.com/tveigaferreira-hue/phyton-.git\n',
 '29. Yasmin Soares - https://github.com/yasminsoares01/aulas-Phyton']

In [13]:
lista_alunos_email = [v[3:].strip().split(" - ") if k < 10 else v[4:].strip().split(" - ") for k, v in enumerate(data_email)]
lista_alunos_email[:4]

[['Aline de Carvalho -'],
 ['Bianca Nichele Kusma', 'bkusma@aluno.fiocruz.br'],
 ['Camilla Leitzke Toledo', 'Camillatoledo453@gmail.com'],
 ['Camilla Maia Moraes -']]

In [14]:
lista_alunos_git = [v[3:].strip().split(" - ") if k < 10 else v[4:].strip().split(" - ") for k, v in enumerate(data_git)]
lista_alunos_git[:4]

[['Alessandra Conti Gomes de Souza',
  'https://github.com/alecgsbr-web/Aula-Phyton'],
 ['Aline de Carvalho', 'https://github.com/aline-bio/python-basico.git'],
 ['Bianca Nichele Kusma', 'https://github.com/biancankusma/python_basico.git'],
 ['Camilla Leitzke Toledo',
  'https://github.com/camilaltoledo0502-art/Entregas-de-atividades-aula-Python-.git']]

In [15]:
data = {
    "alunos": [i[0] for i in lista_alunos_git],
    "github": [i[1] for i in lista_alunos_git],
}
df = pd.DataFrame(data)
df.head()

,alunos,github
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...

In [16]:
df_aulas = df.copy()
for i in exercicios:
    df_aulas.loc[:, i] = False
df_aulas.head()

,alunos,github,02 - Introducao,02 - Introducao,04 - ObjetosSimples,05 - Objetos Compostos 1,06 - Objetos Compostos 2,07 - Operadores Aritmeticos,08 - Operadores Relacionais,09 - Operadores Logicos,10 - Estruturas Condicionais,11 - Estuturas de Repeticao,12 - Rotinas,13 - Variaveis Qualitativas,14- Variaveis Quantitativas,15 - Medidas de Resumo 1,16 - Medidas de Resumo 2
0,Alessandra Conti Gomes de Souza,https://github.com/alecgsbr-web/Aula-Phyton,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,Aline de Carvalho,https://github.com/aline-bio/python-basico.git,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,Bianca Nichele Kusma,https://github.com/biancankusma/python_basico.git,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,Camilla Leitzke Toledo,https://github.com/camilaltoledo0502-art/Entre...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,Camilla Maia Moraes,https://github.com/camss36/Python_b-sico_Camil...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
df_aulas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alunos                        28 non-null     object
 1   github                        28 non-null     object
 2   02 - Introducao               28 non-null     bool
 3   02 - Introducao               28 non-null     bool
 4   04 - ObjetosSimples           28 non-null     bool
 5   05 - Objetos Compostos 1      28 non-null     bool
 6   06 - Objetos Compostos 2      28 non-null     bool
 7   07 - Operadores Aritmeticos   28 non-null     bool
 8   08 - Operadores Relacionais   28 non-null     bool
 9   09 - Operadores Logicos       28 non-null     bool
 10  10 - Estruturas Condicionais  28 non-null     bool
 11  11 - Estuturas de Repeticao   28 non-null     bool
 12  12 - Rotinas                  28 non-null     bool
 13  13 - Variaveis Qualitativas   28 non-null     bool
 14  14-  Variaveis Quantitativas  28 non-null     bool
 15  15 - Medidas de Resumo 1      28 non-null     bool
 16  16 - Medidas de Resumo 2      28 non-null     bool
dtypes: bool(15), object(2)
memory usage: 996.0+ bytes

In [18]:
c = 1
url = df_aulas['github'][c]
print(url)
response = requests.get(url)
if response.status_code == 200:
    data = response.text.split("name")
data = [i for i in data if '.ipynb","' in i]
data = [i.split('","path')[0][3:] for i in data]
data

https://github.com/aline-bio/python-basico.git

['02 - introdução_Aline.ipynb', 'Untitled2.ipynb']