In [71]:
matrix = [
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
]
matrix

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [72]:
matrix[0][0]

1

In [73]:
matrix[0][1]

2

In [74]:
locais = ['sala', 'cozinha', 'quarto', 'banheiro']
lampadas = ['ligada', 'desligada', 'quebrada', 'ligada']
num_lampdas = [2, 1, 1, 3]
testadas = [True, False, False, True]
metros_quadrados = [20.0, 15.2, 10.4, 5.9]

iluminação_1 = {
    'locais': locais,
    'lampadas': lampadas,
    'num_lampdas': num_lampdas,
    'testadas': testadas,
    'metros_quadrados': metros_quadrados
}
iluminação_1

{'locais': ['sala', 'cozinha', 'quarto', 'banheiro'],
 'lampadas': ['ligada', 'desligada', 'quebrada', 'ligada'],
 'num_lampdas': [2, 1, 1, 3],
 'testadas': [True, False, False, True],
 'metros_quadrados': [20.0, 15.2, 10.4, 5.9]}

In [75]:
locais = ('sala', 'cozinha', 'quarto', 'banheiro')
lampadas = ['ligada', 'desligada', 'quebrada', 'ligada']
num_lampdas = (2, 1, 1, 3)
testadas = {
            locais[0]: True, 
            locais[1]: False, 
            locais[2]: False, 
            locais[3]: True
}
metros_quadrados = {20.0, 15.2, 10.4, 5.9}

iluminação_2 = {
    'locais': locais,
    'lampadas': lampadas,
    'num_lampdas': num_lampdas,
    'testadas': testadas,
    'metros_quadrados': metros_quadrados
}
iluminação_2

{'locais': ('sala', 'cozinha', 'quarto', 'banheiro'),
 'lampadas': ['ligada', 'desligada', 'quebrada', 'ligada'],
 'num_lampdas': (2, 1, 1, 3),
 'testadas': {'sala': True,
  'cozinha': False,
  'quarto': False,
  'banheiro': True},
 'metros_quadrados': {5.9, 10.4, 15.2, 20.0}}

In [76]:
print(type(iluminação_2['locais']))
print(type(iluminação_2['lampadas']))
print(type(iluminação_2['num_lampdas']))
print(type(iluminação_2['testadas']))
print(type(iluminação_2['metros_quadrados']))

<class 'tuple'>
<class 'list'>
<class 'tuple'>
<class 'dict'>
<class 'set'>

In [77]:
matrix

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [78]:
matrix[0][0] = "1"
matrix

[['1', 2], [3, 4], [5, 6], [7, 8]]

In [79]:
matrix[1] = "iluminação_2"
matrix

[['1', 2], 'iluminação_2', [5, 6], [7, 8]]

In [82]:
matrix.insert(4, ["iluminação_2", iluminação_2])
matrix

[['1', 2],
 'iluminação_2',
 [5, 6],
 [7, 8],
 ['iluminação_2',
  {'locais': ('sala', 'cozinha', 'quarto', 'banheiro'),
   'lampadas': ['ligada', 'desligada', 'quebrada', 'ligada'],
   'num_lampdas': (2, 1, 1, 3),
   'testadas': {'sala': True,
    'cozinha': False,
    'quarto': False,
    'banheiro': True},
   'metros_quadrados': {5.9, 10.4, 15.2, 20.0}}]]

In [83]:
import pandas as pd
import numpy as np

In [136]:
id = 'testadas'
array = np.array(iluminação_2['locais'])
array = np.append(array, iluminação_2['lampadas'])
array = np.append(array, iluminação_2['num_lampdas'])
array = np.append(array, [
                    iluminação_2[id][list(iluminação_2[id].keys())[0]],
                    iluminação_2[id][list(iluminação_2[id].keys())[1]],
                    iluminação_2[id][list(iluminação_2[id].keys())[2]],
                    iluminação_2[id][list(iluminação_2[id].keys())[3]]
                ]
)
array = array.reshape(4, -1)
array

array([['sala', 'cozinha', 'quarto', 'banheiro'],
       ['ligada', 'desligada', 'quebrada', 'ligada'],
       ['2', '1', '1', '3'],
       ['True', 'False', 'False', 'True']], dtype='<U21')

In [137]:
type(array)

numpy.ndarray

In [138]:
array.shape

(4, 4)

In [149]:
num_vetor = np.random.randint(0, 10, 9)
num_vetor

array([2, 8, 5, 8, 7, 2, 6, 0, 9])

In [ ]:
num_matrix = np.random.randint(
                    0, 
                    10,
                    size=(3, 3)
)
num_matrix

array([[7, 2, 0],
       [0, 4, 2],
       [2, 0, 9]])

In [147]:
num_array = np.array((
    num_matrix,
    num_matrix,
    num_matrix,
))
num_array

array([[[7, 2, 0],
        [0, 4, 2],
        [2, 0, 9]],

       [[7, 2, 0],
        [0, 4, 2],
        [2, 0, 9]],

       [[7, 2, 0],
        [0, 4, 2],
        [2, 0, 9]]])

In [148]:
num_array.shape

(3, 3, 3)

In [151]:
df = pd.DataFrame(num_matrix)
df

   0  1  2
0  7  2  0
1  0  4  2
2  2  0  9

In [153]:
import os
os.listdir()

['aulas', 'data', 'exercicios']

In [155]:
df = pd.read_csv('./data/data.csv')
df.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1